import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createRequire } from 'node:module';
const require=createRequire(new URL('../server/package.json',import.meta.url));
const {io}=createRequire(new URL('../client/package.json',import.meta.url))('socket.io-client');
const Database=require('better-sqlite3');
const port=15100+Math.floor(Math.random()*500),base=`http://127.0.0.1:${port}`;
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'meuapp-auth-')),sqlite=path.join(temp,'data.db');
const child=spawn(process.execPath,['server/src/server.js'],{env:{...process.env,SQLITE_PATH:sqlite,DATABASE_URL:'',HOST:'127.0.0.1',PORT:String(port)},windowsHide:true,stdio:['ignore','pipe','pipe']});
let logs='';child.stdout.on('data',d=>logs+=d);child.stderr.on('data',d=>logs+=d);
async function request(method,url,token,body) {
  const r=await fetch(base+url,{method,headers:{...(token?{Authorization:`Bearer ${token}`} : {}),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});
  let data;try{data=await r.json();}catch{}return {status:r.status,data};
}
const once=(socket,event)=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error(`Timeout ${event}`)),5000);socket.once(event,value=>{clearTimeout(timer);resolve(value);});});
async function connect(token) {const s=io(base,{auth:{token},transports:['websocket'],autoConnect:false});const ready=once(s,'connect');s.connect();await ready;return s;}
test('real authenticated accounts, friendship, private persistence, permissions and revocation',async t=>{
  const sockets=[];
  t.after(()=>{for(const s of sockets)s.close();child.kill();});
  for(let i=0;i<100;i++){try{if((await request('GET','/api/health')).status===200)break;}catch{}await new Promise(r=>setTimeout(r,100));if(i===99)throw Error(logs);}
  assert.equal((await request('GET','/api/servers')).status,401);
  const accounts=[];
  for(const handle of ['alice','bruno','carol']) {const r=await request('POST','/api/auth/register',null,{handle,password:'Test-password-12345',username:handle});assert.equal(r.status,201,JSON.stringify(r.data));accounts.push(r.data);}
  const [a,b,c]=accounts;
  assert.equal((await request('POST','/api/auth/login',null,{handle:'alice',password:'incorrect-password'})).status,401);
  assert.equal((await request('POST','/api/auth/login',null,{handle:'alice',password:'Test-password-12345'})).data.user.id,a.user.id);
  const sa=await connect(a.token),sb=await connect(b.token),sc=await connect(c.token);sockets.push(sa,sb,sc);
  sa.emit('user_join',{id:b.user.id,username:'Impersonator'});
  assert.equal((await request('POST','/api/users/sync',a.token,{id:b.user.id,username:'stolen'})).status,403);
  const pending=once(sb,'friend_request');assert.equal((await request('POST','/api/friends/requests',a.token,{handle:'bruno'})).status,201);assert.equal((await pending).user.id,a.user.id);
  assert.equal((await request('PUT',`/api/friends/${b.user.id}/accept`,a.token)).status,409);
  assert.equal((await request('PUT',`/api/friends/${a.user.id}/accept`,b.token)).status,204);
  assert.equal((await request('GET','/api/friends',a.token)).data[0].state,'accepted');
  const dm=(await request('POST','/api/dms',a.token,{userId:b.user.id})).data.id;
  assert.equal((await request('GET',`/api/dms/${dm}/messages`,c.token)).status,403);
  assert.equal((await request('PUT',`/api/dms/${dm}/read`,c.token)).status,403);
  const received=once(sb,'dm_message');const ack=await sa.timeout(5000).emitWithAck('dm_send',{conversationId:dm,content:'Olá, ação e coração',senderId:c.user.id});assert.equal(ack.ok,true);
  const message=await received;assert.equal(message.sender.id,a.user.id);assert.equal(message.content,'Olá, ação e coração');
  assert.equal((await request('GET',`/api/dms/${dm}/messages`,b.token)).data[0].id,message.id);
  assert.equal((await request('GET','/api/dms',b.token)).data[0].unread,1);
  assert.match((await sc.timeout(5000).emitWithAck('dm_send',{conversationId:dm,content:'intrusion'})).error,/privada/);
  assert.equal((await request('PUT',`/api/blocks/${a.user.id}`,b.token)).status,204);
  assert.match((await sa.timeout(5000).emitWithAck('dm_send',{conversationId:dm,content:'blocked'})).error,/bloqueada/);
  assert.equal((await request('DELETE',`/api/blocks/${a.user.id}`,b.token)).status,204);
  assert.equal((await request('POST','/api/friends/requests',a.token,{handle:'bruno'})).status,201);
  assert.equal((await request('DELETE',`/api/friends/${a.user.id}`,b.token)).status,204,'recipient can reject a pending request');
  assert.deepEqual((await request('GET','/api/friends',a.token)).data,[]);
  assert.equal((await request('POST','/api/friends/requests',a.token,{handle:'bruno'})).status,201);
  assert.equal((await request('PUT',`/api/friends/${a.user.id}/accept`,b.token)).status,204);
  assert.equal((await request('DELETE',`/api/friends/${b.user.id}`,a.token)).status,204,'accepted friend can be removed');
  assert.deepEqual((await request('GET','/api/friends',b.token)).data,[]);
  assert.equal((await request('POST','/api/friends/requests',a.token,{handle:'bruno'})).status,201);
  assert.equal((await request('PUT',`/api/friends/${a.user.id}/accept`,b.token)).status,204);
  const privateServer=(await request('POST','/api/servers',a.token,{name:'Private',ownerId:b.user.id})).data;assert.equal(privateServer.owner_id,a.user.id);
  assert.ok(!(await request('GET','/api/servers',b.token)).data.some(s=>s.id===privateServer.id));
  const ch=privateServer.channels.find(c=>c.type==='text'),voice=privateServer.channels.find(c=>c.type==='voice');
  assert.equal((await request('GET',`/api/channels/${ch.id}/messages`,b.token)).status,403);
  assert.equal((await request('PUT',`/api/servers/${privateServer.id}`,b.token,{name:'hijack'})).status,403);
  assert.equal((await request('POST',`/api/servers/${privateServer.id}/channels`,b.token,{name:'hijack',type:'voice'})).status,403);
  assert.ok((await sb.timeout(5000).emitWithAck('join_voice_channel',{channelId:voice.id})).error);
  const invite=(await request('POST',`/api/servers/${privateServer.id}/invites`,a.token)).data.code;
  assert.equal((await request('POST',`/api/invites/${invite}/join`,b.token)).status,200);
  assert.equal((await sb.timeout(5000).emitWithAck('join_voice_channel',{channelId:voice.id})).ok,true);
  assert.equal((await sa.timeout(5000).emitWithAck('join_voice_channel',{channelId:voice.id})).ok,true);
  const called=once(sb,'call_invitation');assert.equal((await sa.timeout(5000).emitWithAck('call_invite',{channelId:voice.id,userId:b.user.id,user:c.user})).ok,true);assert.equal((await called).user.id,a.user.id);
  const started=once(sb,'screen_share_started');sa.emit('voice_state_toggle',{channelId:voice.id,isScreenSharing:true,canAssist:true,assistanceMode:'desktop'});await started;
  const viewing=once(sa,'screen_request_view');sb.emit('screen_request_view',{channelId:voice.id,targetSocketId:sa.id});await viewing;
  const assistance=once(sa,'interaction_request');assert.equal((await sb.timeout(5000).emitWithAck('interaction_request',{sessionId:'authenticated-assistance',targetSocketId:sa.id,fromUser:c.user})).ok,true);
  assert.equal((await assistance).fromUser.id,b.user.id,'assistance displays the authenticated requester, ignoring the claimed identity');
  assert.equal((await request('PUT',`/api/blocks/${a.user.id}`,c.token)).status,204);
  const consent=await sa.timeout(5000).emitWithAck('interaction_consent',{sessionId:'authenticated-assistance',targetSocketId:sb.id,approved:true});
  assert.equal(consent.ok,true,'a third party blocking the host cannot cancel consent between the host and guest');
  sa.emit('interaction_ready',{sessionId:'authenticated-assistance',targetSocketId:sb.id});
  const revoked=once(sb,'interaction_revoke');
  assert.equal((await request('PUT',`/api/blocks/${a.user.id}`,b.token)).status,204);await revoked;
  assert.equal((await request('DELETE',`/api/blocks/${a.user.id}`,b.token)).status,204);
  const form=new FormData();form.append('file',new Blob(['private attachment']),'private.txt');
  const uploaded=await fetch(base+'/api/upload',{method:'POST',headers:{Authorization:`Bearer ${a.token}`},body:form});const file=await uploaded.json();assert.equal(uploaded.status,200);
  assert.equal((await request('GET',file.url,c.token)).status,403);assert.equal((await request('GET',file.url)).status,401);
  assert.equal((await sa.timeout(5000).emitWithAck('send_message',{channelId:ch.id,content:'private',attachment:file})).ok,true);
  assert.equal((await request('GET',file.url,b.token)).status,200);assert.equal((await request('GET',file.url,c.token)).status,403);
  const database=new Database(sqlite,{readonly:true});assert.equal(database.prepare('SELECT content FROM dm_messages WHERE id=?').get(message.id).content,message.content);assert.equal(database.prepare('SELECT count(*) AS n FROM schema_migrations').get().n,6);database.close();
  const disconnect=once(sa,'disconnect');assert.equal((await request('DELETE','/api/auth/session',a.token)).status,204);await disconnect;
  assert.equal((await request('GET','/api/auth/me',a.token)).status,401);
});
