import crypto from 'node:crypto';
import db from './db.js';
import {route,fail} from './auth.js';
import {requirePermission,serverMembership,accessibleChannel,audit} from './permissions.js';
import {conversationAccess} from './conversations.js';

export async function assetAccess(userId,id,tx=db) {
  const a=await tx.queryOne('SELECT * FROM server_assets WHERE id=$1 AND deleted_at IS NULL',[id]);if(!a)return null;
  if(a.owner_id===userId || a.server_id && await serverMembership(userId,a.server_id,tx))return a;
  const patterns=[`%<:%:${a.id}>%`,`%[[sticker:${a.id}]]%`];
  for(const row of await tx.query('SELECT channel_id FROM messages WHERE deleted_at IS NULL AND (content LIKE $1 OR content LIKE $2) LIMIT 100',patterns))if(await accessibleChannel(userId,row.channel_id,'text','readHistory',tx))return a;
  for(const table of ['dm_messages','group_messages'])for(const row of await tx.query(`SELECT conversation_id FROM ${table} WHERE deleted_at IS NULL AND (content LIKE $1 OR content LIKE $2) LIMIT 100`,patterns))try{await conversationAccess(userId,row.conversation_id,tx);return a;}catch{}
  for(const row of await tx.query('SELECT t.channel_id FROM thread_messages m JOIN threads t ON t.id=m.thread_id WHERE m.deleted_at IS NULL AND t.deleted_at IS NULL AND (m.content LIKE $1 OR m.content LIKE $2) LIMIT 100',patterns))if(await accessibleChannel(userId,row.channel_id,'text','readHistory',tx))return a;
  for(const[kind,table,field]of [['channels','messages','channel_id'],['dms','dm_messages','conversation_id'],['dms','group_messages','conversation_id'],['threads','thread_messages','thread_id']])for(const row of await tx.query(`SELECT m.${field} AS context_id FROM message_reactions r JOIN ${table} m ON m.id=r.message_id WHERE r.kind=$1 AND r.emoji=$2 AND m.deleted_at IS NULL LIMIT 100`,[kind,`asset:${a.id}`])){if(kind==='channels' && await accessibleChannel(userId,row.context_id,'text','readHistory',tx))return a;if(kind==='dms')try{await conversationAccess(userId,row.context_id,tx);return a;}catch{}if(kind==='threads'){const t=await tx.queryOne('SELECT channel_id FROM threads WHERE id=$1 AND deleted_at IS NULL',[row.context_id]);if(t && await accessibleChannel(userId,t.channel_id,'text','readHistory',tx))return a;}}
  return null;
}
export async function validateAssetReferences(userId,content,channel=null,tx=db) {
  for(const match of content.matchAll(/<:([^:>]+):([\w-]+)>|\[\[sticker:([\w-]+)\]\]/g)){
    const id=match[2] || match[3],kind=match[2]?'emoji':'sticker';if(kind==='sticker' && ['party','wave','heart'].includes(id))continue;
    const asset=await assetAccess(userId,id,tx);if(!asset || asset.kind!==kind)fail(403,'Emoji ou sticker indisponível');if(channel && asset.server_id!==channel.server_id && !channel.permissions.useExternalEmoji)fail(403,'Emojis externos não são permitidos neste canal');
  }
}

export function installCommunityMedia(app,io) {
  const validKind=kind=>{if(!['emoji','sticker','gif','sound'].includes(kind))fail(400,'Tipo de mídia inválido');};
  app.get('/api/assets/:id',route(async(req,res)=>{const a=await assetAccess(req.user.id,req.params.id);if(!a)fail(403,'Mídia indisponível');res.json(a);}));
  app.get('/api/assets',route(async(req,res)=>{
    const kind=String(req.query.kind || 'emoji');validKind(kind);const serverId=req.query.serverId;if(serverId && !await serverMembership(req.user.id,serverId))fail(403,'Servidor indisponível');
    const rows=await db.query('SELECT * FROM server_assets WHERE kind=$1 AND deleted_at IS NULL ORDER BY created_at DESC',[kind]),out=[];for(const asset of rows)if(serverId?asset.server_id===serverId:asset.owner_id===req.user.id || asset.server_id && await serverMembership(req.user.id,asset.server_id))out.push(asset);const q=String(req.query.q || '').toLowerCase();res.json(out.filter(a=>!q || a.name.toLowerCase().includes(q)).slice(0,200));
  }));
  app.post('/api/assets',route(async(req,res)=>{
    const b=req.body;validKind(b.kind);if(typeof b.name!=='string' || !b.name.trim() || b.name.length>80)fail(400,'Nome inválido');if(b.serverId)await requirePermission(req.user.id,b.serverId,'manageAssets');
    const filename=typeof b.url==='string' && b.url.match(/^\/uploads\/([\w.-]+)$/)?.[1],upload=filename && await db.queryOne('SELECT * FROM upload_records WHERE filename=$1 AND owner_id=$2',[filename,req.user.id]);if(!upload || upload.profile_user_id || upload.channel_id || upload.conversation_id || upload.server_id || upload.feature_id)fail(403,'Envie um novo arquivo para esta mídia');
    if(b.kind==='sound'?!upload.mimetype?.startsWith('audio/'):!upload.mimetype?.startsWith('image/'))fail(400,'Tipo de arquivo incompatível com a mídia');if(b.kind==='gif' && upload.mimetype!=='image/gif')fail(400,'Escolha um GIF');
    const id=crypto.randomUUID();await db.transaction(async tx=>{await tx.query('INSERT INTO server_assets(id,server_id,kind,name,url,owner_id,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[id,b.serverId || null,b.kind,b.name,b.url,req.user.id,new Date().toISOString()]);await tx.query('UPDATE upload_records SET feature_id=$1,server_id=$2 WHERE filename=$3',[id,b.serverId || null,filename]);if(b.serverId)await audit(tx,b.serverId,req.user.id,'asset.create',id,{kind:b.kind,name:b.name});});io.to(b.serverId?`server_${b.serverId}`:`user_${req.user.id}`).emit('assets_changed',{kind:b.kind});res.status(201).json({id});
  }));
  app.delete('/api/assets/:id',route(async(req,res)=>{const asset=await db.queryOne('SELECT * FROM server_assets WHERE id=$1 AND deleted_at IS NULL',[req.params.id]);if(!asset)fail(404,'Mídia indisponível');if(asset.server_id)await requirePermission(req.user.id,asset.server_id,'manageAssets');else if(asset.owner_id!==req.user.id)fail(403,'Mídia privada');await db.query('UPDATE server_assets SET deleted_at=$1 WHERE id=$2',[new Date().toISOString(),asset.id]);io.to(asset.server_id?`server_${asset.server_id}`:`user_${req.user.id}`).emit('assets_changed',{kind:asset.kind});res.sendStatus(204);}));
  app.get('/api/servers/:id/events',route(async(req,res)=>{if(!await serverMembership(req.user.id,req.params.id))fail(403,'Servidor indisponível');const rows=await db.query('SELECT e.*,u.username FROM scheduled_events e JOIN users u ON u.id=e.creator_id WHERE e.server_id=$1 AND e.deleted_at IS NULL ORDER BY e.starts_at',[req.params.id]);const visible=[];for(const e of rows)if(!e.channel_id || await accessibleChannel(req.user.id,e.channel_id)){e.interests=await db.query('SELECT user_id FROM event_interests WHERE event_id=$1',[e.id]);visible.push(e);}res.json(visible);}));
  app.post('/api/servers/:id/events',route(async(req,res)=>{
    await requirePermission(req.user.id,req.params.id,'manageEvents');const b=req.body;if(typeof b.name!=='string' || !b.name.trim() || b.name.length>100 || !Number.isFinite(Date.parse(b.startsAt)) || Date.parse(b.startsAt)<=Date.now())fail(400,'Informe nome e data futura válidos');if(b.channelId){const c=await accessibleChannel(req.user.id,b.channelId);if(!c || c.server_id!==req.params.id)fail(400,'Canal inválido');}if(b.endsAt && (!Number.isFinite(Date.parse(b.endsAt)) || Date.parse(b.endsAt)<=Date.parse(b.startsAt)))fail(400,'Fim do evento inválido');const id=crypto.randomUUID();await db.transaction(async tx=>{await tx.query('INSERT INTO scheduled_events(id,server_id,channel_id,name,description,starts_at,ends_at,creator_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[id,req.params.id,b.channelId || null,b.name,String(b.description || '').slice(0,2000),new Date(b.startsAt).toISOString(),b.endsAt?new Date(b.endsAt).toISOString():null,req.user.id]);await audit(tx,req.params.id,req.user.id,'event.create',id);});io.to(`server_${req.params.id}`).emit('events_changed',{});res.status(201).json({id});
  }));
  app.put('/api/events/:id/interest',route(async(req,res)=>{const e=await db.queryOne('SELECT * FROM scheduled_events WHERE id=$1 AND deleted_at IS NULL',[req.params.id]);if(!e || !await serverMembership(req.user.id,e.server_id) || e.channel_id && !await accessibleChannel(req.user.id,e.channel_id))fail(403,'Evento indisponível');if(req.body.interested===false)await db.query('DELETE FROM event_interests WHERE event_id=$1 AND user_id=$2',[e.id,req.user.id]);else await db.query('INSERT INTO event_interests(event_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[e.id,req.user.id]);io.to(`server_${e.server_id}`).emit('events_changed',{});res.sendStatus(204);}));
  app.delete('/api/events/:id',route(async(req,res)=>{const e=await db.queryOne('SELECT * FROM scheduled_events WHERE id=$1 AND deleted_at IS NULL',[req.params.id]);if(!e)fail(404,'Evento indisponível');await requirePermission(req.user.id,e.server_id,'manageEvents');await db.query('UPDATE scheduled_events SET deleted_at=$1 WHERE id=$2',[new Date().toISOString(),e.id]);io.to(`server_${e.server_id}`).emit('events_changed',{});res.sendStatus(204);}));
  const notified=new Map();let polling=false;
  const remind=async()=>{if(polling)return;polling=true;try{const now=Date.now(),events=await db.query('SELECT * FROM scheduled_events WHERE deleted_at IS NULL AND starts_at>$1 AND starts_at<=$2',[new Date(now-60000).toISOString(),new Date(now+300000).toISOString()]);for(const e of events)for(const p of await db.query('SELECT user_id FROM event_interests WHERE event_id=$1',[e.id]))if(await serverMembership(p.user_id,e.server_id) && (!e.channel_id || await accessibleChannel(p.user_id,e.channel_id)) && io.sockets.adapter.rooms.get(`user_${p.user_id}`)?.size && !notified.has(`${e.id}:${p.user_id}`)){io.to(`user_${p.user_id}`).emit('event_reminder',{id:e.id,name:e.name,startsAt:e.starts_at,serverId:e.server_id,channelId:e.channel_id});notified.set(`${e.id}:${p.user_id}`,now);}for(const[key,time]of notified)if(time<now-600000)notified.delete(key);}catch(e){console.error('[Event reminder]',e.message);}finally{polling=false;}};
  const timer=setInterval(remind,30000);timer.unref();
  return {close:()=>clearInterval(timer)};
}
