import db from './db.js';
import {route,fail,visibleUser} from './auth.js';
import {messageContext} from './message-features.js';
import {accessibleChannel,serverMembership} from './permissions.js';
export function installMentions(app){
 app.get('/api/conversation/:kind/:id/mentions',route(async(req,res)=>{const c=await messageContext(req.user.id,req.params.kind,req.params.id),result=[];const users=c.channel?await db.query('SELECT u.*,a.login_name FROM users u JOIN server_members m ON m.user_id=u.id LEFT JOIN auth_accounts a ON a.user_id=u.id WHERE m.server_id=$1',[c.channel.server_id]):await db.query(`SELECT u.*,a.login_name FROM users u JOIN ${c.conversation.membersTable} p ON p.user_id=u.id LEFT JOIN auth_accounts a ON a.user_id=u.id WHERE p.conversation_id=$1 AND p.state='accepted'`,[c.id]);for(const u of users){const visible=await visibleUser(req.user.id,u);result.push({trigger:'@',label:visible.handle || visible.username,value:`<@${u.id}>`});}if(c.channel){for(const r of await db.query('SELECT id,name FROM roles WHERE server_id=$1',[c.channel.server_id]))result.push({trigger:'@',label:r.name,value:`<@&${r.id}>`});for(const row of await db.query('SELECT id,name FROM channels WHERE server_id=$1 AND deleted_at IS NULL',[c.channel.server_id]))if(await accessibleChannel(req.user.id,row.id))result.push({trigger:'#',label:row.name,value:`<#${row.id}>`});if(c.channel.permissions.mentionEveryone)for(const name of ['everyone','here'])result.push({trigger:'@',label:name,value:`@${name}`});}res.json(result);
 }));
 app.get('/api/mentions/resolve',route(async(req,res)=>{const type=req.query.type,id=String(req.query.id || '');if(type==='channel'){const c=await accessibleChannel(req.user.id,id);if(!c)fail(403,'Canal indisponível');res.json({name:c.name,channelId:c.id,serverId:c.server_id});}else if(type==='role'){const r=await db.queryOne('SELECT id,name,server_id FROM roles WHERE id=$1',[id]);if(!r || !await serverMembership(req.user.id,r.server_id))fail(403,'Cargo indisponível');res.json({name:r.name});}else{const u=await db.queryOne('SELECT u.*,a.login_name FROM users u JOIN auth_accounts a ON a.user_id=u.id WHERE u.id=$1 OR a.login_name=$1',[id.replace(/^@/,'')]);if(!u)fail(404,'Pessoa indisponível');const p=await visibleUser(req.user.id,u);res.json({id:p.id,name:p.handle || p.username,username:p.username,handle:p.handle});}}));
}
