import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),asar=require('@electron/asar');
const output=path.resolve(process.argv[2] || 'dist'),packaged=path.resolve(process.argv[3] || path.join(output,'win-unpacked')),archive=path.join(packaged,'resources/app.asar');
const hash=data=>crypto.createHash('sha256').update(data).digest('hex');
const helper=path.join(packaged,'resources/app.asar.unpacked/desktop/NativeInputHost.exe');
assert.equal(hash(fs.readFileSync(helper)),hash(fs.readFileSync('desktop/NativeInputHost.exe')),'Packaged native helper differs from freshly compiled helper');
assert.equal(asar.statFile(archive,'desktop/NativeInputHost.exe').unpacked,true);
const audioHelper=path.join(packaged,'resources/app.asar.unpacked/desktop/AudioSessionHost.exe');assert.equal(hash(fs.readFileSync(audioHelper)),hash(fs.readFileSync('desktop/AudioSessionHost.exe')));assert.equal(asar.statFile(archive,'desktop/AudioSessionHost.exe').unpacked,true);
const sourceFiles=[...fs.readdirSync('desktop',{recursive:true}).filter(file=>/\.(?:js|cjs|cs)$/.test(file) && fs.statSync(path.join('desktop',file)).isFile()).map(file=>path.join('desktop',file)),...fs.readdirSync('client/dist',{recursive:true}).filter(file=>fs.statSync(path.join('client/dist',file)).isFile()).map(file=>path.join('client/dist',file))];
for(const file of sourceFiles)assert.equal(hash(asar.extractFile(archive,path.normalize(file))),hash(fs.readFileSync(file)),`Stale packaged file: ${file}`);
const pkg=JSON.parse(asar.extractFile(archive,'package.json').toString()),source=JSON.parse(fs.readFileSync('package.json'));
assert.equal(pkg.version,source.version);
const installer=path.join(output,`MeuApp-Setup-${pkg.version}.exe`);assert.ok(fs.statSync(installer).size>10000000);
const yaml=require('js-yaml');
const feed=yaml.load(fs.readFileSync(path.join(output,'latest.yml'),'utf8'));
assert.equal(feed.version,pkg.version);
assert.equal(feed.files[0].url,path.basename(installer));
assert.equal(feed.files[0].sha512,crypto.createHash('sha512').update(fs.readFileSync(installer)).digest('base64'));
const provider=yaml.load(fs.readFileSync(path.join(packaged,'resources/app-update.yml'),'utf8'));
assert.equal(provider.provider,'github');assert.equal(provider.owner,source.build.publish[0].owner);assert.equal(provider.repo,source.build.publish[0].repo);
const report={version:pkg.version,installer,kind:'NSIS installer, Windows x64',builtAt:fs.statSync(installer).mtime.toISOString(),builtAtSaoPaulo:fs.statSync(installer).mtime.toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}),installerSha256:hash(fs.readFileSync(installer)),helperSha256:hash(fs.readFileSync(helper)),helperPath:helper,asarMatchesSource:true,updateMetadataMatchesInstaller:true,updateProvider:provider};
fs.mkdirSync('docs/validation',{recursive:true});fs.writeFileSync('docs/validation/build.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
