import {t as translate,useLocale} from '../localization';
import React,{useState,useEffect} from 'react';
import api from '../api';
import {useAuth} from '../context/AuthContext';
import {Field,Action,Notice} from './FormControls';
export default function AccountSettings() {
  useLocale();
  const {currentUser,updateProfile,logout}=useAuth();
  const [info,setInfo]=useState(null),[sessions,setSessions]=useState([]),[password,setPassword]=useState(''),[code,setCode]=useState(''),[handle,setHandle]=useState(currentUser.handle),[email,setEmail]=useState(''),[newPassword,setNewPassword]=useState(''),[setup,setSetup]=useState(null),[codes,setCodes]=useState([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  async function refresh(){const [a,s]=await Promise.all([api.get('/api/account'),api.get('/api/account/sessions')]);setInfo(a.data);setSessions(s.data);setEmail(a.data.email || '');}
  useEffect(()=>{refresh().catch(e=>setError(e.response?.data?.error || 'Não foi possível carregar a conta'));},[]);
  async function run(fn,success='Alteração salva'){setBusy(true);setError('');setMessage('');try{await fn();setMessage(success);await refresh();}catch(e){setError(e.response?.data?.error || 'Não foi possível concluir a alteração');}finally{setBusy(false);}}
  const credentials={password,code};
  return <div className="space-y-6"><h3 className="font-bold text-lg">{translate("Conta e segurança")}</h3><p className="text-sm text-discord-textMuted">{translate("Confirme sua senha atual para alterar os dados da conta.")}</p><Field label={translate("Senha atual")} type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/>{info?.twoFactor&&<Field label={translate("Código do autenticador")} value={code} onChange={e=>setCode(e.target.value)}/>}<Notice error={error} message={message}/>
    <section className="space-y-3 border-b border-discord-active pb-5"><Field label={translate("Nome de usuário (@)")} maxLength={32} value={handle} onChange={e=>setHandle(e.target.value)}/><Action disabled={busy || !password} onClick={()=>run(async()=>{await api.put('/api/account/handle',{...credentials,handle});await updateProfile({});})}>{translate("Alterar usuário")}</Action></section>
    <section className="space-y-3 border-b border-discord-active pb-5"><Field label={translate("Nova senha")} type="password" minLength={12} autoComplete="new-password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/><Action disabled={busy || !password || newPassword.length<12} onClick={()=>run(async()=>{await api.put('/api/account/password',{...credentials,newPassword});await logout();},'Senha alterada. Entre novamente.')}>{translate("Alterar senha e encerrar sessões")}</Action></section>
    <section className="space-y-3 border-b border-discord-active pb-5"><Field label={translate("E-mail")} type="email" value={email} onChange={e=>setEmail(e.target.value)}/><p className="text-xs">{info?.emailVerified?'E-mail confirmado':'E-mail não confirmado'}</p>{info && !info.mail&&<p className="text-sm text-discord-textMuted">{translate("O envio de confirmação por e-mail ainda está indisponível neste servidor.")}</p>}<Action disabled={busy || !password || !info?.mail || !email} onClick={()=>run(()=>api.put('/api/account/email',{...credentials,email}),'Enviamos um código para confirmar o novo e-mail.')}>{translate("Confirmar ou alterar e-mail")}</Action><EmailConfirmation/></section>
    <section className="space-y-3 border-b border-discord-active pb-5"><h4 className="font-semibold">{translate("Autenticação em dois fatores")}</h4><p className="text-sm">{info?.twoFactor?'Ativada':'Desativada'}</p>{!info?.twoFactor?<><Action disabled={busy || !password} onClick={()=>run(async()=>setSetup((await api.post('/api/account/two-factor/setup',credentials)).data),'Adicione a chave ao seu aplicativo autenticador.')}>{translate("Configurar autenticador")}</Action>{setup&&<><Field label={translate("Chave do autenticador")} readOnly value={setup.secret}/><a href={setup.uri} target="_blank" rel="noopener noreferrer" className="text-discord-blurple underline text-sm">{translate("Abrir no autenticador")}</a><Field label={translate("Código de 6 dígitos")} inputMode="numeric" value={code} onChange={e=>setCode(e.target.value)}/><Action disabled={busy || !/^\d{6}$/.test(code)} onClick={()=>run(async()=>{const r=await api.post('/api/account/two-factor/enable',{code});setCodes(r.data.recoveryCodes);setSetup(null);},'Autenticação ativada. Guarde os códigos de recuperação.')}>{translate("Ativar")}</Action></>}</>:<Action danger disabled={busy || !password || !code} onClick={()=>run(()=>api.delete('/api/account/two-factor',{data:credentials}))}>{translate("Desativar autenticador")}</Action>}{codes.length>0&&<div className="bg-discord-darkest p-4 rounded"><p className="text-sm mb-2">{translate("Guarde estes códigos em um local seguro. Cada um funciona uma única vez.")}</p><pre className="select-text text-xs">{codes.join('\n')}</pre><Action onClick={()=>{const blob=new Blob([codes.join('\n')],{type:'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='meuapp-codigos-recuperacao.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>{translate("Salvar códigos")}</Action></div>}</section>
    <section className="space-y-3 border-b border-discord-active pb-5"><h4 className="font-semibold">{translate("Dispositivos e sessões")}</h4>{sessions.map(s=><div key={s.id} className="bg-discord-darker p-3 rounded text-sm"><b>{s.current?'Este dispositivo':'Outro dispositivo'}</b><p className="break-words text-xs text-discord-textMuted">{s.device}</p><p className="text-xs">{s.createdAt?new Date(s.createdAt).toLocaleString():'Sessão anterior'} {translate("· expira")} {new Date(s.expiresAt).toLocaleString()}</p>{!s.current&&<button onClick={()=>run(()=>api.delete(`/api/account/sessions/${s.id}`))} className="text-discord-red mt-2">{translate("Encerrar sessão")}</button>}</div>)}<Action disabled={busy} onClick={()=>run(()=>api.delete('/api/account/other-sessions'))}>{translate("Encerrar outras sessões")}</Action></section>
    <section className="space-y-3"><h4 className="font-semibold">{translate("Desativar ou excluir conta")}</h4><p className="text-sm text-discord-textMuted">{translate("Desativar permite reativar no próximo login. Excluir impede novos acessos; o histórico existente é preservado.")}</p>{['disable','delete'].map(action=><Action key={action} danger disabled={busy || !password} onClick={()=>{if(window.confirm(action==='disable'?'Desativar a conta e encerrar todas as sessões?':'Excluir sua conta permanentemente?'))run(async()=>{await api.post(`/api/account/${action}`,credentials);await logout();});}}>{action==='disable'?'Desativar temporariamente':'Excluir conta'}</Action>)}</section>
  </div>;
}
function EmailConfirmation(){
  useLocale();const[token,setToken]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');return <div className="space-y-2"><Field label={translate("Código recebido por e-mail")} value={token} onChange={e=>setToken(e.target.value)}/><Action disabled={!token} onClick={async()=>{try{await api.post('/api/account/verify-email',{token});setMessage('E-mail confirmado.');setError('');setToken('');}catch(e){setError(e.response?.data?.error || 'Código inválido');}}}>{translate("Confirmar código")}</Action><Notice error={error} message={message}/></div>;}
export function AccountRecovery({onClose}) {
  useLocale();
  const params=new URLSearchParams(window.location.search),[email,setEmail]=useState(''),[token,setToken]=useState(params.get('token') || ''),[newPassword,setPassword]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),purpose=params.get('accountAction');
  async function run(fn,notice){setBusy(true);setError('');try{await fn();setMessage(notice);}catch(e){setError(e.response?.data?.error || 'Não foi possível recuperar a conta');}finally{setBusy(false);}}
  return <section className="w-full max-w-md p-8 rounded-xl bg-discord-chat text-discord-textNormal space-y-4"><h1 className="font-bold text-xl">{purpose==='email'?'Confirmar e-mail':'Recuperar conta'}</h1>{purpose!=='email'&&<><Field label={translate("E-mail confirmado da conta")} type="email" value={email} onChange={e=>setEmail(e.target.value)}/><Action disabled={busy || !email} onClick={()=>run(()=>api.post('/api/account/recovery',{email}),'Se o endereço estiver confirmado, você receberá um código.')}>{translate("Enviar recuperação")}</Action></>}<Field label={translate("Código recebido")} value={token} onChange={e=>setToken(e.target.value)}/>{purpose!=='email'&&<Field label={translate("Nova senha (mínimo 12 caracteres)")} type="password" value={newPassword} onChange={e=>setPassword(e.target.value)}/>}<Action disabled={busy || !token || purpose!=='email' && newPassword.length<12} onClick={()=>run(()=>api.post(purpose==='email'?'/api/account/verify-email':'/api/account/reset-password',{token,newPassword}),purpose==='email'?'E-mail confirmado.':'Senha alterada. Entre usando a nova senha.')}>{purpose==='email'?'Confirmar e-mail':'Redefinir senha'}</Action><Notice error={error} message={message}/><button onClick={onClose} className="text-discord-blurple text-sm">{translate("Voltar ao login")}</button></section>;
}
