import {t as translate,useLocale} from '../localization';
import React,{useState,useEffect,useRef} from 'react';
import {useVoice} from '../context/VoiceContext';
import {useAudioPreferences} from '../context/AudioPreferencesContext';
import {Toggle,Action,Notice} from './FormControls';
export default function AudioSettings(){
 useLocale();const{devices,refreshDevices,changeInputDevice,changeOutputDevice}=useVoice(),{settings,update,reset}=useAudioPreferences();
 const[testing,setTesting]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState(''),[level,setLevel]=useState(0),[preview,setPreview]=useState(null),[previewPending,setPreviewPending]=useState(false),[hearTest,setHearTest]=useState(false);
 const test=useRef(null),video=useRef(null),audio=useRef(null),previewRef=useRef(null),micEpoch=useRef(0),cameraEpoch=useRef(0),mounted=useRef(true);
 function stopTest(render=true){micEpoch.current++;const s=test.current;test.current=null;if(s){clearInterval(s.timer);s.stream.getTracks().forEach(t=>t.stop());s.destination.stream.getTracks().forEach(t=>t.stop());s.context.close().catch(()=>{});}if(render&&mounted.current){setTesting(false);setPending(false);setLevel(0);}}
 function stopPreview(render=true){cameraEpoch.current++;previewRef.current?.getTracks().forEach(t=>t.stop());previewRef.current=null;if(render&&mounted.current){setPreview(null);setPreviewPending(false);}}
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;stopTest(false);stopPreview(false);};},[]);
 useEffect(()=>{if(video.current)video.current.srcObject=preview;},[preview]);
 useEffect(()=>{const s=test.current;if(s){s.gain.gain.value=settings.inputGain;s.output.gain.value=settings.outputGain;}if(audio.current){audio.current.muted=!hearTest;audio.current.setSinkId?.(settings.outputDeviceId || '').catch(()=>setError('Saída de áudio indisponível'));}},[settings.inputGain,settings.outputGain,settings.outputDeviceId,hearTest,testing]);
 async function start(){stopTest();const epoch=micEpoch.current;setPending(true);setError('');let stream,context,destination;try{stream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:settings.inputDeviceId?{exact:settings.inputDeviceId}:undefined,echoCancellation:settings.echoCancellation,noiseSuppression:settings.noiseSuppression,autoGainControl:settings.autoGainControl}});if(!mounted.current || epoch!==micEpoch.current){stream.getTracks().forEach(t=>t.stop());return;}context=new AudioContext();const source=context.createMediaStreamSource(stream),gain=context.createGain(),output=context.createGain(),analyser=context.createAnalyser();destination=context.createMediaStreamDestination();gain.gain.value=settings.inputGain;output.gain.value=settings.outputGain;source.connect(gain);gain.connect(analyser);analyser.connect(output);output.connect(destination);await context.resume();if(!mounted.current || epoch!==micEpoch.current){stream.getTracks().forEach(t=>t.stop());destination.stream.getTracks().forEach(t=>t.stop());context.close().catch(()=>{});return;}const data=new Uint8Array(analyser.fftSize),timer=setInterval(()=>{analyser.getByteTimeDomainData(data);setLevel(Math.min(100,Math.round(Math.sqrt(data.reduce((sum,v)=>sum+((v-128)/128)**2,0)/data.length)*350)));},80);test.current={stream,context,gain,output,timer,destination};setTesting(true);setPending(false);await refreshDevices();requestAnimationFrame(()=>{if(audio.current && test.current?.stream===stream){audio.current.srcObject=destination.stream;audio.current.play().catch(()=>setError('Clique em Ouvir teste para ativar a reprodução.'));}});}catch{stream?.getTracks().forEach(t=>t.stop());destination?.stream.getTracks().forEach(t=>t.stop());context?.close().catch(()=>{});if(mounted.current && epoch===micEpoch.current){setPending(false);setError('Não foi possível testar o microfone. Verifique as permissões do dispositivo.');}}}
 async function openPreview(){stopPreview();const epoch=cameraEpoch.current;setPreviewPending(true);try{const stream=await navigator.mediaDevices.getUserMedia({video:{deviceId:settings.cameraDeviceId?{exact:settings.cameraDeviceId}:undefined},audio:false});if(!mounted.current || epoch!==cameraEpoch.current){stream.getTracks().forEach(t=>t.stop());return;}previewRef.current=stream;setPreview(stream);setPreviewPending(false);await refreshDevices();}catch{if(mounted.current && epoch===cameraEpoch.current){setPreviewPending(false);setError('Não foi possível abrir a webcam selecionada.');}}}
 return <div className="space-y-5"><h3 className="font-bold text-lg">{translate('Voz, câmera e dispositivos')}</h3>{[['audioinput','inputDeviceId','Microfone'],['audiooutput','outputDeviceId','Alto-falante / headset'],['videoinput','cameraDeviceId','Webcam']].map(([kind,key,label])=><label key={key} className="block text-sm">{translate(label)}<select aria-label={translate(label)} value={settings[key]} onChange={e=>{if(key==='inputDeviceId'){stopTest();changeInputDevice(e.target.value);}else if(key==='outputDeviceId')changeOutputDevice(e.target.value);else{stopPreview();update({[key]:e.target.value});}}} className="block bg-discord-darkest p-3 rounded w-full mt-2"><option value="">{translate('Padrão do sistema')}</option>{devices.filter(d=>d.kind===kind).map((d,i)=><option key={d.deviceId || i} value={d.deviceId}>{d.label || `${translate(label)} ${i+1}`}</option>)}</select></label>)}
 {[['inputGain','Volume de entrada'],['outputGain','Volume de saída']].map(([key,label])=><label key={key} className="block text-sm">{translate(label)}: {Math.round(settings[key]*100)}%<input aria-label={translate(label)} type="range" min={0} max={2} step={0.05} value={settings[key]} onChange={e=>update({[key]:Number(e.target.value)})} className="block w-full mt-2"/></label>)}
 <Action onClick={()=>testing||pending?stopTest():start()}>{translate(testing||pending?'Parar teste':'Testar microfone')}</Action>{testing&&<><progress aria-label={translate('Nível do microfone')} max={100} value={level} className="block w-full"/><Toggle label="Ouvir teste" checked={hearTest} onChange={value=>{setHearTest(value);if(value)audio.current?.play().catch(()=>setError('Reprodução do teste indisponível'));}}/><audio ref={audio} autoPlay muted={!hearTest}/></>}
 <label className="block text-sm">{translate('Modo de entrada')}<select aria-label={translate('Modo de entrada')} value={settings.mode} onChange={e=>update({mode:e.target.value})} className="block bg-discord-darkest p-3 rounded w-full mt-2"><option value="open">{translate('Microfone aberto')}</option><option value="voice">{translate('Atividade de voz')}</option><option value="ptt">Push-to-Talk</option></select></label><Toggle label={translate('Sensibilidade automática')} checked={settings.autoSensitivity} onChange={v=>update({autoSensitivity:v})}/>{!settings.autoSensitivity&&<label className="block text-sm">{translate('Sensibilidade manual')}<input aria-label={translate('Sensibilidade manual')} type="range" min={0.001} max={0.25} step={0.001} value={settings.sensitivity} onChange={e=>update({sensitivity:Number(e.target.value)})} className="block w-full mt-2"/></label>}
 <label className="block text-sm">{translate('Tecla Push-to-Talk')}<input readOnly aria-label={translate('Tecla Push-to-Talk')} value={settings.pttKey} onKeyDown={e=>{e.preventDefault();if(!['Control','Alt','Shift','Meta'].includes(e.key))update({pttKey:[e.ctrlKey?'Control':null,e.altKey?'Alt':null,e.shiftKey?'Shift':null,e.metaKey?'Meta':null,e.code].filter(Boolean).join('+')});}} className="bg-discord-darkest p-3 rounded mt-2 block w-full"/></label>{[['noiseSuppression','Supressão / redução de ruído'],['echoCancellation','Cancelamento de eco'],['autoGainControl','Ganho automático'],['qos','Prioridade dos pacotes de áudio']].map(([key,label])=><Toggle key={key} label={translate(label)} checked={settings[key]} onChange={v=>update({[key]:v})}/>)}
 <label className="block text-sm">{translate('Atenuação quando alguém fala:')} {Math.round(settings.attenuation*100)}%<input aria-label={translate('Atenuação')} type="range" min={0} max={1} step={0.05} value={settings.attenuation} onChange={e=>update({attenuation:Number(e.target.value)})} className="block w-full mt-2"/></label><Action disabled={previewPending} onClick={openPreview}>{translate('Prévia da câmera')}</Action>{previewPending&&<Action onClick={()=>stopPreview()}>{translate('Cancelar')}</Action>}{preview&&<><video ref={video} autoPlay muted playsInline className="w-full rounded max-h-56"/><Action onClick={()=>stopPreview()}>{translate('Fechar prévia')}</Action></>}<Action onClick={()=>{stopTest();stopPreview();reset();}}>{translate('Restaurar configurações de áudio')}</Action><Notice error={error}/></div>;
}
