import {t as translate,useLocale} from '../localization';
import UnreadMark from './UnreadMark';
import React,{useState} from 'react';
import {useVoice} from '../context/VoiceContext';
import {useSocket} from '../context/SocketContext';
import api from '../api';
export default function CategorizedChannels({server,onSelectChannel,onOpenProfile}) {
  useLocale();
  const{joinVoice,currentVoiceChannel,startWatchingScreen}=useVoice(),{voiceRooms,isConnected}=useSocket();const[collapsed,setCollapsed]=useState(()=>{try{return JSON.parse(localStorage.getItem(`categories:${server.id}`)) || [];}catch{return [];}}),[error,setError]=useState('');
  const toggle=id=>setCollapsed(old=>{const value=old.includes(id)?old.filter(x=>x!==id):[...old,id];localStorage.setItem(`categories:${server.id}`,JSON.stringify(value));return value;});
  async function drop(e,category){e.preventDefault();const id=e.dataTransfer.getData('application/meuapp-channel');if(!id || !server.permissions?.manageChannels)return;try{const channel=server.channels.find(c=>c.id===id);await api.patch(`/api/servers/${server.id}/channels/${id}`,{category_id:category.id,position:0,name:channel.name});setError('');}catch(e){setError(e.response?.data?.error || 'Não foi possível mover');}}
  return <>{error&&<p role="alert" className="text-discord-red text-xs">{error}</p>}{(server.categories || []).map(category=><section key={category.id} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,category)}><button type="button" onClick={()=>toggle(category.id)} className="text-xs font-bold uppercase w-full text-left p-2" aria-expanded={!collapsed.includes(category.id)}>{collapsed.includes(category.id)?'▸':'▾'} {category.name}</button>{!collapsed.includes(category.id)&&server.channels.filter(c=>c.category_id===category.id).map(c=><div key={c.id} draggable={!!server.permissions?.manageChannels} onDragStart={e=>e.dataTransfer.setData('application/meuapp-channel',c.id)}><button type="button" disabled={c.type==='voice' && !isConnected} className={`w-full flex items-center gap-2 text-sm p-2 rounded hover:bg-discord-hover ${currentVoiceChannel?.id===c.id?'text-discord-green':''}`} onClick={async()=>{if(c.type==='voice' && !await joinVoice(c))return;onSelectChannel(c);}}>{c.type==='voice'?'🔊':'#'} {c.name}<UnreadMark channelId={c.id}/></button>{(voiceRooms[c.id] || []).map(p=><div key={p.socketId} className="text-xs pl-6 flex gap-2 py-1"><button onClick={()=>onOpenProfile(p.user)}>{p.isSpeaking?'◉':''} {p.user.username} {p.isMuted?'🔇':''} {p.isDeafened?'🎧':''}</button>{p.isScreenSharing&&<button className="text-discord-green" onClick={async()=>{if(await joinVoice(c)){onSelectChannel(c);startWatchingScreen(p.socketId);}}}>{translate("Assistir")}</button>}</div>)}</div>)}</section>)}</>;
}
