import React,{useEffect,useRef} from 'react';
import {useVoice} from '../context/VoiceContext';
import {useSocket} from '../context/SocketContext';
import {useSocial} from '../context/SocialContext';
import {useAudioPreferences} from '../context/AudioPreferencesContext';
import {usePreferences} from '../context/PreferencesContext';
export default function DesktopRuntime({channel}){
 const voice=useVoice(),social=useSocial(),{socket,voiceRooms}=useSocket(),{settings}=useAudioPreferences(),{preferences}=usePreferences();
 const latest=useRef({voice,social,channel,socket,settings,preferences,voiceRooms}),recent=useRef([]);latest.current={voice,social,channel,socket,settings,preferences,voiceRooms};
 useEffect(()=>{recent.current=[];},[channel?.id,social.selectedDm]);
 useEffect(()=>{const api=window.electronAPI?.desktop;if(!api)return;const clean=api.onAction(action=>{const{voice,social}=latest.current;if(action==='mute')voice.toggleMute();else if(action==='deafen')voice.toggleDeafen();else if(action==='share')voice.toggleScreenShare();else if(action==='acceptCall')social.respondCall('accept');else if(action==='declineCall')social.respondCall('decline');});
 const quick=api.onQuickChat(async text=>{const{channel,social,socket}=latest.current;if(!socket?.connected)return;const dm=!channel && social.selectedDm,kind=dm?'dm_send':'send_message',context=dm?{conversationId:dm}:{channelId:channel?.id};if(!dm && channel?.type!=='text')return;try{const r=await socket.timeout(10000).emitWithAck(kind,{...context,content:text});if(r.error)social.setError(r.error);}catch{social.setError('Mensagem rápida não confirmada. Confira o histórico.');}});return()=>{clean();quick();};},[]);
 useEffect(()=>{if(!socket)return;const message=m=>{const state=latest.current;if(m.channelId===state.channel?.id || m.conversationId===state.social.selectedDm)recent.current=[...recent.current.slice(-4),{name:m.sender.username,text:m.content}];};socket.on('new_message',message);socket.on('dm_message',message);return()=>{socket.off('new_message',message);socket.off('dm_message',message);};},[socket]);
 useEffect(()=>{const api=window.electronAPI?.desktop;if(!api)return;const update=()=>{const{voice,social,channel,settings,preferences,voiceRooms}=latest.current;api.runtime({active:!!voice.currentVoiceChannel,chatActive:channel?.type==='text'||!!social.selectedDm,channel:voice.currentVoiceChannel?.name || '',muted:voice.isMuted,deafened:voice.isDeafened,sharing:voice.isScreenSharing,participants:(voiceRooms[voice.currentVoiceChannel?.id] || []).map(p=>({name:p.user.username,speaking:voice.speakingParticipants[p.socketId]??p.isSpeaking,muted:p.isMuted,deafened:p.isDeafened})),messages:preferences.notificationPreview?recent.current:[],remoteSpeaking:!voice.isDeafened && (voiceRooms[voice.currentVoiceChannel?.id] || []).some(p=>p.socketId!==latest.current.socket?.id && (voice.speakingParticipants[p.socketId]??p.isSpeaking) && !settings.participants[p.user.id]?.muted),attenuation:settings.attenuation,ptt:{enabled:settings.mode==='ptt',binding:settings.pttKey}}).catch(()=>{});};update();const timer=setInterval(update,1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{const api=window.electronAPI?.desktop;if(!api || !socket)return;let alive=true,running=false,lastPresence='',lastPresenceAt=0;const poll=async()=>{if(running || !socket.connected)return;running=true;try{const p=latest.current.social.notificationSettings.preferences || {},[idle,apps]=await Promise.all([api.idleSeconds(),p.detectActivity?api.runningApps():Promise.resolve([])]);if(!alive)return;const allowed=p.activityPrograms || [],app=apps.filter(a=>allowed.includes(a.name)).sort((a,b)=>String(b.startedAt).localeCompare(String(a.startedAt)))[0];const state={idle:idle>=300,activity:app?.name || '',startedAt:app?.startedAt || null},key=JSON.stringify(state);if(key!==lastPresence || Date.now()-lastPresenceAt>=300000){lastPresence=key;lastPresenceAt=Date.now();socket.emit('presence_runtime',state);}}catch{}finally{running=false;}};poll();const timer=setInterval(poll,10000);return()=>{alive=false;clearInterval(timer);};},[socket]);
 return null;
}
