import {t as translate,useLocale} from '../localization';
import React,{useEffect,useRef} from 'react';
export const Field=({label,...props})=><label className="form-field block text-sm space-y-2"><span>{translate(label)}</span><input aria-label={translate(label)} {...props} className={`block w-full rounded bg-discord-darkest p-3 ${props.className || ''}`}/></label>;
export const Action=({children,danger=false,...props})=><button type="button" {...props} className={`form-action rounded px-4 py-2 text-sm disabled:opacity-40 ${danger?'bg-discord-red text-white':'bg-discord-blurple text-white'} ${props.className || ''}`}>{children}</button>;
export const Notice=({error,message})=><>{error&&<p role="alert" className="text-discord-red text-sm py-2">{error}</p>}{message&&<p role="status" className="text-discord-green text-sm py-2">{message}</p>}</>;
export const Toggle=({label,checked,onChange,detail})=><label className="form-toggle flex gap-3 items-center py-2 text-sm"><input aria-label={translate(label)} type="checkbox" checked={!!checked} onChange={e=>onChange(e.target.checked)}/><span>{translate(label)}{detail&&<small className="block text-discord-textMuted">{translate(detail)}</small>}</span></label>;
export function Modal({title,onClose,children,wide=false}) {
  useLocale();
  const ref=useRef(null);
  useEffect(()=>{const previous=document.activeElement;ref.current?.querySelector('button,input,select,textarea')?.focus();const key=e=>{if(e.key==='Escape'){e.stopPropagation();onClose();}if(e.key==='Tab'){const all=[...ref.current.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href],[tabindex="0"]')].filter(el=>el.offsetParent!==null);if(!all.length){e.preventDefault();return;}if(e.shiftKey && document.activeElement===all[0]){all.at(-1).focus();e.preventDefault();}else if(!e.shiftKey && document.activeElement===all.at(-1)){all[0].focus();e.preventDefault();}}};ref.current.addEventListener('keydown',key);const node=ref.current;return()=>{node.removeEventListener('keydown',key);previous?.focus?.();};},[]);
  return <div className="fixed inset-0 bg-black/75 z-[70] p-4 flex items-center justify-center" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section ref={ref} role="dialog" aria-modal="true" aria-label={title} className={`bg-discord-chat text-discord-textNormal rounded-xl shadow-2xl w-full max-h-[92vh] overflow-auto p-6 ${wide?'max-w-5xl':'max-w-xl'}`}><header className="flex justify-between items-center gap-4 mb-5"><h2 className="font-bold text-xl text-discord-textHeader">{title}</h2><button type="button" aria-label={`Fechar ${title}`} onClick={onClose}>✕</button></header>{children}</section></div>;
}
