import {t as translate,useLocale} from '../localization';
import PrivateChat,{CreateGroup} from './PrivateChat';
import {MessageActions,MessageEdit,DeleteMessageDialog,useMessageChanges} from './MessageTools';
import {InviteCard} from './ServerInvites';
import {getPreferences} from '../preferences';
import React,{useState,useEffect,useRef} from 'react';
import { Users,MessageCircle,Check,X,UserPlus,Phone,Video,Shield } from 'lucide-react';
import { useSocial } from '../context/SocialContext';
import { useSocket } from '../context/SocketContext';
import { useAuth } from '../context/AuthContext';
import { useVoice } from '../context/VoiceContext';
import api from '../api';
import ProtectedImage from './ProtectedImage';
export function DirectMessageList() {
  useLocale();
  const {conversations,selectedDm,setSelectedDm,directUnread:unread}=useSocial();
  const [group,setGroup]=useState(false);
  return <div className="p-3 space-y-1 overflow-auto"><button onClick={()=>setSelectedDm(null)} className={`w-full flex items-center gap-3 p-3 rounded ${!selectedDm?'bg-discord-active text-white':'text-discord-textMuted'}`}><Users size={20}/>{translate("Amigos")}{unread>0&&<span className="ml-auto bg-red-500 text-white text-xs rounded-full px-2">{unread}</span>}</button><button type="button" onClick={()=>setGroup(true)} className="text-discord-blurple text-xs p-2">{translate("Criar grupo")}</button>{[['requested','Solicitações'],['spam','Spam']].map(([state,label])=><button key={state} type="button" className="block text-xs p-2" onClick={()=>{setSelectedDm(null);window.dispatchEvent(new CustomEvent('open-message-requests',{detail:label}));}}>{translate(label)} ({conversations.filter(c=>c.state===state).length})</button>)}<p className="text-xs font-bold text-discord-textMuted pt-4 pb-2">{translate("MENSAGENS DIRETAS")}</p>{conversations.filter(c=>c.state==='accepted').map(c=><button key={c.id} data-testid={`dm-open-${c.user.handle}`} onClick={()=>setSelectedDm(c.id)} className={`w-full p-2 rounded flex items-center gap-2 hover:bg-discord-hover ${selectedDm===c.id?'bg-discord-active text-white':'text-discord-textMuted'}`}><Avatar user={c.kind==='group'?{username:c.name,avatar:c.icon}:c.user}/><span className="truncate">{c.kind==='group'?c.name:c.user.username}</span>{c.unread>0&&<b className="ml-auto rounded-full px-2 text-xs bg-red-500 text-white">{c.unread}</b>}</button>)}{group&&<CreateGroup onClose={()=>setGroup(false)}/>}</div>;
}
function Avatar({user}) {
  useLocale();return user.avatar?<ProtectedImage src={user.avatar} alt="" className="w-9 h-9 rounded-full"/>:<span className="w-9 h-9 rounded-full bg-discord-blurple text-white flex items-center justify-center shrink-0">{Array.from(user.username || '?')[0].toUpperCase()}</span>;}
export default function FriendsHome() {
  useLocale();
  const {friends,selectedDm,conversations,setSelectedDm,openDm,act,error,setError,invitation,setInvitation,callUser,startCall}=useSocial();
  const {socket}=useSocket(),{currentVoiceChannel}=useVoice();
  const [tab,setTab]=useState('Online'),[handle,setHandle]=useState(''),[success,setSuccess]=useState(''),[friendQuery,setFriendQuery]=useState('');
  useEffect(()=>{const show=e=>{setSelectedDm(null);setTab(e.detail);};window.addEventListener('open-message-requests',show);return()=>window.removeEventListener('open-message-requests',show);},[setSelectedDm]);
  const dm=conversations.find(c=>c.id===selectedDm);
  const filtered=friends.filter(f=>tab==='Todos'?f.state==='accepted':tab==='Online'?f.state==='accepted' && f.status!=='offline':tab==='Pendentes'?f.state==='pending':tab==='Bloqueados'?f.state==='blocked':false).filter(f=>`${f.username} ${f.handle}`.toLowerCase().includes(friendQuery.toLowerCase()));
  const run=fn=>Promise.resolve().then(fn).catch(()=>{});
  function invite(f) {run(()=>callUser(f));}
  return <section className="flex-1 min-w-0 flex flex-col bg-discord-chat text-discord-textNormal">
    {invitation&&<div className="px-5 py-3 bg-discord-blurple/30 flex gap-3 items-center"><Phone size={18}/><span>{invitation.user.username} {translate("convidou você para")} {invitation.channel.name}</span><button className="ml-auto bg-discord-blurple px-3 py-1 rounded" onClick={()=>{window.dispatchEvent(new CustomEvent('navigate-channel',{detail:{channelId:invitation.channel.id,serverId:invitation.channel.server_id,join:true}}));setInvitation(null);}}>{translate("Entrar")}</button><button onClick={()=>setInvitation(null)}><X size={18}/></button></div>}
    {selectedDm?<><header className="conversation-header"><MessageCircle size={20}/><b>{dm?.kind==='group'?dm.name:dm?.user.username || 'Conversa privada'}</b><button title={translate("Iniciar chamada de áudio")} className="conversation-call" onClick={()=>startCall(selectedDm,false).catch(()=>{})}><Phone size={18}/></button><button title={translate("Iniciar chamada de vídeo")} className="conversation-call" onClick={()=>startCall(selectedDm,true).catch(()=>{})}><Video size={19}/></button><button className="ml-auto text-sm text-discord-textMuted" onClick={()=>setSelectedDm(null)}>{translate("Amigos")}</button></header><DmChat key={selectedDm} id={selectedDm} conversation={dm}/></>:<>
      <header className="h-14 border-b border-black/20 flex items-center px-5 gap-3 shrink-0 overflow-x-auto whitespace-nowrap"><Users size={22}/><b>{translate("Amigos")}</b><span className="h-6 border-r border-white/10"/>{['Online','Todos','Pendentes','Bloqueados','Adicionar amigo'].map(t=><button key={translate(t)} data-testid={`friends-tab-${translate(t)}`} onClick={()=>{setTab(t);setError('');setSuccess('');}} className={`text-sm px-2 py-1 rounded ${t==='Adicionar amigo'?'bg-[#248046] text-white':tab===t?'bg-discord-active text-white':'text-discord-textMuted'}`}>{translate(t)}{t==='Pendentes'&&friends.some(f=>f.state==='pending')?` (${friends.filter(f=>f.state==='pending').length})`:''}</button>)}</header>
      <div className="p-6 flex-1 overflow-auto">{['Solicitações','Spam'].includes(tab)?<RequestInbox state={tab==='Spam'?'spam':'requested'}/>:tab==='Adicionar amigo'?<form onSubmit={e=>{e.preventDefault();run(async()=>{await act('post','/api/friends/requests',{handle});setSuccess('Solicitação enviada');setHandle('');});}}><h2 className="font-bold text-white">{translate("ADICIONAR AMIGO")}</h2><p className="text-sm text-discord-textMuted mt-2 mb-4">{translate("Digite o nome de usuário da conta.")}</p><div className="flex gap-3 bg-discord-darkest border border-white/10 p-3 rounded-lg"><input data-testid="friend-handle" required value={handle} onChange={e=>setHandle(e.target.value)} placeholder={translate("nome.de.usuario")} className="flex-1 min-w-0 bg-transparent outline-none"/><button data-testid="friend-send" className="bg-discord-blurple rounded px-4 py-2 text-sm text-white">{translate("Enviar solicitação")}</button></div></form>:<><input aria-label={translate("Pesquisar amigo")} placeholder={translate("Pesquisar amigo")} value={friendQuery} onChange={e=>setFriendQuery(e.target.value)} className="bg-discord-darkest p-3 rounded text-sm mb-4 w-full"/><h2 className="text-xs font-bold text-discord-textMuted uppercase mb-4">{tab} — {filtered.length}</h2>{filtered.length===0?<div className="text-center text-discord-textMuted py-24"><Users size={48} className="mx-auto mb-5 opacity-40"/><p>{tab==='Online'?translate("Nenhum amigo online agora. Adicione alguém para começar."):translate("Nada por aqui ainda.")}</p></div>:filtered.map(f=><div key={f.id} data-testid={`friend-${f.handle}`} className="border-t border-white/10 flex items-center gap-3 py-4 hover:bg-white/5 rounded px-2"><Avatar user={f}/><div><div className="font-semibold text-white">{f.username}<span className="ml-2 text-xs font-normal text-discord-textMuted">@{f.handle}</span></div><p className="text-xs text-discord-textMuted">{f.state==='pending'?(f.direction==='incoming'?translate("Solicitação recebida"):translate("Solicitação enviada")):f.state==='blocked'?'Bloqueado':{online:'Disponível',idle:'Ausente',dnd:'Não perturbe',offline:'Offline'}[f.status]}</p></div><div className="ml-auto flex gap-2">
        {f.state==='accepted'&&<><button title={translate("Abrir conversa")} data-testid={`friend-dm-${f.handle}`} onClick={()=>run(()=>openDm(f))} className="p-2 bg-discord-darker rounded-full"><MessageCircle size={20}/></button><button title={translate("Convidar para chamada")} onClick={()=>invite(f)} className="p-2 bg-discord-darker rounded-full"><Phone size={20}/></button><button title={translate("Bloquear")} onClick={()=>run(()=>act('put',`/api/blocks/${f.id}`))} className="p-2 bg-discord-darker rounded-full"><Shield size={20}/></button></>}
        {f.state==='pending'&&f.direction==='incoming'&&<button title={translate("Aceitar")} data-testid={`friend-accept-${f.handle}`} onClick={()=>run(()=>act('put',`/api/friends/${f.id}/accept`))} className="p-2 bg-discord-darker text-green-400 rounded-full"><Check size={20}/></button>}
        <button title={f.state==='blocked'?translate("Desbloquear"):f.state==='accepted'?translate("Remover amigo"):translate("Recusar / cancelar")} onClick={()=>run(()=>act('delete',f.state==='blocked'?`/api/blocks/${f.id}`:`/api/friends/${f.id}`))} className="p-2 bg-discord-darker rounded-full text-red-300"><X size={20}/></button>
      </div></div>)}</>}{error&&<p role="alert" className="text-red-300 text-sm mt-4">{error}</p>}{success&&<p role="status" className="text-green-300 text-sm mt-4">{success}</p>}</div>
    </>}
  </section>;
}
function DmChat(props){
  useLocale();return <PrivateChat {...props}/>;}
function RequestInbox({state}){
  useLocale();const{conversations,act,setSelectedDm,setError}=useSocial();return <div className="space-y-3"><h2 className="font-bold">{state==='spam'?'Spam':translate("Solicitações de mensagem")}</h2>{conversations.filter(c=>c.state===state).map(c=><article key={c.id} className="bg-discord-darker p-4 rounded"><b>{c.user.username}</b><p className="text-sm my-2">{c.lastMessage?.content}</p><div className="flex gap-3 text-sm"><button onClick={()=>setSelectedDm(c.id)}>{translate("Ver conversa")}</button>{[['accept','Aceitar'],['ignore','Ignorar'],['block','Bloquear'],...(state==='requested'?[['spam','Marcar spam']]:[])].map(([action,label])=><button key={action} onClick={()=>act('put',`/api/dms/${c.id}/request`,{action}).catch(e=>setError(e.response?.data?.error || 'Ação indisponível'))} className="text-discord-blurple">{translate(label)}</button>)}</div></article>)}</div>;}
