import {t as translate,useLocale} from '../localization';
import React,{useEffect,useState} from 'react';
import api from '../api';
import {requestMessageNavigation} from '../message-navigation';
import {Modal,Field,Action,Notice} from './FormControls';
import {useSocial} from '../context/SocialContext';
export default function GlobalSearch(){
  useLocale();const[open,setOpen]=useState(false),[q,setQ]=useState(''),[results,setResults]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);const{setSelectedDm}=useSocial();
 useEffect(()=>{const key=e=>{if((e.ctrlKey || e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(v=>!v);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const navigate=async r=>{setError('');if(r.type==='user'){window.dispatchEvent(new CustomEvent('open-user-profile',{detail:{id:r.id,username:r.username}}));}else if(r.kind==='dms' || r.type==='conversation'){setSelectedDm(r.contextId || r.id);window.dispatchEvent(new Event('navigate-home'));if(r.id&&r.type==='message')requestMessageNavigation(r);}else{window.dispatchEvent(new CustomEvent('navigate-channel',{detail:{channelId:r.type==='channel'?r.id:r.channelId || (r.kind==='channels'?r.contextId:null),serverId:r.serverId}}));if(r.type==='message')requestMessageNavigation(r);}setOpen(false);};
 return <><button type="button" className="fixed bottom-3 left-3 z-30 bg-discord-darker rounded px-3 py-2 text-xs" title={translate("Buscar (Ctrl+K)")} onClick={()=>setOpen(true)}>{translate("⌕ Buscar")}</button>{open&&<Modal title={translate("Buscar no aplicativo")} onClose={()=>setOpen(false)}><form className="space-y-3" onSubmit={async e=>{e.preventDefault();setBusy(true);try{setResults((await api.get('/api/search',{params:{q}})).data);setError('');}catch(e){setError(e.response?.data?.error || 'Busca indisponível');}finally{setBusy(false);}}}><Field label={translate("Mensagem, canal, conversa ou pessoa")} value={q} minLength={2} maxLength={200} onChange={e=>setQ(e.target.value)}/><Action type="submit" disabled={busy || q.trim().length<2}>{busy?'Buscando…':translate("Buscar")}</Action><Notice error={error}/></form><div className="mt-4 space-y-2 max-h-96 overflow-auto">{results.map((r,i)=><button key={`${r.type}:${r.id}:${i}`} onClick={()=>navigate(r)} className="block w-full text-left bg-discord-darker p-3 rounded"><b>{r.type==='message'?r.sender.username:r.name || r.username}</b><small className="block text-discord-textMuted">{({message:'Mensagem',channel:'Canal',user:'Pessoa',conversation:'Conversa'})[r.type]}{r.timestamp?' · '+new Date(r.timestamp).toLocaleString():''}</small><p className="text-sm whitespace-pre-wrap">{r.content?.slice(0,300)}</p></button>)}</div></Modal>}</>;
}
