import {t as translate,useLocale} from '../localization';
import React,{useState,useEffect,useRef} from 'react';
import api from '../api';
import {useAuth} from '../context/AuthContext';
import {Modal,Field,Action,Notice} from './FormControls';
import ProtectedImage from './ProtectedImage';
const EMOJIS=[['😀','sorriso feliz'],['😂','risada'],['❤️','amor coração'],['👍','positivo jóia'],['🔥','fogo'],['🎉','festa'],['👀','olhos'],['😎','óculos'],['😭','chorando'],['🤔','pensando'],['🚀','foguete'],['🎮','jogo'],['🍕','pizza'],['✨','brilho'],['🙌','comemorar'],['👋','aceno'],['💯','cem'],['💖','coração rosa'],['🤖','robô'],['💀','caveira'],['🤝','aperto de mãos'],['🌈','arco íris']];
export default function MediaPicker({onClose,onSelect,initial='emoji',allowedKinds=['emoji','gif','sticker']}) {
  useLocale();
  const{currentUser}=useAuth();const[kind,setKind]=useState(initial),[query,setQuery]=useState(''),[scope,setScope]=useState('all'),[assets,setAssets]=useState([]),[name,setName]=useState(''),[file,setFile]=useState(null),[error,setError]=useState('');const key=`media-library:${currentUser.id}`,read=()=>{try{const value=JSON.parse(localStorage.getItem(key));return value && Array.isArray(value.recent) && Array.isArray(value.favorite)?value:{recent:[],favorite:[]};}catch{return{recent:[],favorite:[]};}};const[saved,setSaved]=useState(read);
  const persist=value=>{setSaved(value);localStorage.setItem(key,JSON.stringify(value));};
  const refresh=()=>api.get('/api/assets',{params:{kind,q:query}}).then(r=>setAssets(r.data));useEffect(()=>{refresh().catch(e=>setError(e.response?.data?.error || 'Mídia indisponível'));},[kind,query]);
  const select=async item=>{persist({...saved,recent:[item.key,...saved.recent.filter(k=>k!==item.key)].slice(0,40)});try{await onSelect(item);onClose();}catch(e){setError(e.response?.data?.error || e.message);}};
  const favorite=item=>persist({...saved,favorite:saved.favorite.includes(item.key)?saved.favorite.filter(k=>k!==item.key):[...saved.favorite,item.key].slice(0,100)});
  const builtin=kind==='emoji'?EMOJIS.map(([value,name])=>({key:`emoji:${value}`,kind,value,name})):kind==='sticker'?[['party','🎉','Festa'],['wave','👋','Aceno'],['heart','💖','Coração']].map(([id,value,name])=>({key:`sticker:${id}`,kind,value:`[[sticker:${id}]]`,label:value,name})):[];
  const items=[...builtin,...assets.map(a=>({key:`asset:${a.id}`,kind,id:a.id,url:a.url,name:a.name,value:kind==='emoji'?`<:${a.name.replace(/\W/g,'_')}:${a.id}>`:kind==='sticker'?`[[sticker:${a.id}]]`:a.url}))].filter(item=>(!query || `${item.name} ${item.value}`.toLowerCase().includes(query.toLowerCase())) && (scope==='all' || saved[scope].includes(item.key)));
  if(scope==='recent')items.sort((a,b)=>saved.recent.indexOf(a.key)-saved.recent.indexOf(b.key));
  return <Modal title={translate("Emojis, GIFs e stickers")} onClose={onClose}><div className="flex gap-2 mb-3">{[['emoji','Emojis'],['gif','GIFs'],['sticker','Stickers']].filter(([kind])=>allowedKinds.includes(kind)).map(([v,t])=><Action key={v} onClick={()=>setKind(v)}>{translate(t)}</Action>)}</div><Field label={translate("Buscar")} value={query} onChange={e=>setQuery(e.target.value)}/><div className="flex gap-3 text-sm my-3">{[['all','Todos'],['recent','Recentes'],['favorite','Favoritos']].map(([v,t])=><button type="button" key={v} aria-pressed={scope===v} onClick={()=>setScope(v)} className={scope===v?'text-discord-blurple font-bold':''}>{translate(t)}</button>)}</div><div className="grid grid-cols-5 gap-2 max-h-64 overflow-auto">{items.map(item=><div key={item.key} className="relative bg-discord-darker rounded p-2"><button type="button" aria-label={`Enviar ${item.name}`} title={item.name} onClick={()=>select(item)} className="w-full h-16 text-3xl flex items-center justify-center">{item.url?<ProtectedImage src={item.url} alt={item.name} className="w-full h-full object-contain"/>:item.label || item.value}</button><button type="button" aria-label={`Favoritar ${item.name}`} onClick={()=>favorite(item)} className="absolute top-0 right-1 text-xs">{saved.favorite.includes(item.key)?'★':'☆'}</button></div>)}</div><details className="mt-5"><summary className="text-sm cursor-pointer">{translate("Adicionar")} {kind==='emoji'?'emoji':kind==='gif'?'GIF':'sticker'} {translate("personalizado")}</summary><div className="space-y-3 mt-3"><Field label={translate("Nome")} value={name} onChange={e=>setName(e.target.value)}/><input type="file" accept={kind==='gif'?'image/gif':'image/*'} aria-label={translate("Arquivo de mídia")} onChange={e=>setFile(e.target.files[0])}/><Action disabled={!name.trim() || !file} onClick={async()=>{try{const form=new FormData();form.append('file',file);const upload=await api.post('/api/upload',form);await api.post('/api/assets',{kind,name,url:upload.data.url});await refresh();setName('');setFile(null);}catch(e){setError(e.response?.data?.error || 'Falha no envio');}}}>{translate("Adicionar à biblioteca")}</Action></div></details><Notice error={error}/></Modal>;
}
export function VoiceRecorder({onFile,onError,disabled=false}) {
  useLocale();
  const[recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),state=useRef(null),generation=useRef(0);
  useEffect(()=>()=>{generation.current++;const s=state.current;if(s){s.recorder.onstop=null;if(s.recorder.state!=='inactive')s.recorder.stop();s.stream.getTracks().forEach(t=>t.stop());clearInterval(s.timer);}state.current=null;},[]);
  async function start(){const epoch=++generation.current;try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true}});if(epoch!==generation.current){stream.getTracks().forEach(t=>t.stop());return;}const mime=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'';const recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined),chunks=[];let size=0,count=0;recorder.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);size+=e.data.size;if(size>=10*1024*1024 && recorder.state==='recording')recorder.stop();}};const timer=setInterval(()=>{setSeconds(++count);if(count>=120 && recorder.state==='recording')recorder.stop();},1000);recorder.onstop=()=>{clearInterval(timer);stream.getTracks().forEach(t=>t.stop());state.current=null;setRecording(false);if(epoch===generation.current && size>0 && size<=10*1024*1024)onFile(new File(chunks,`mensagem-de-voz-${Date.now()}.webm`,{type:recorder.mimeType || 'audio/webm'}));else if(size>10*1024*1024)onError('Mensagem de voz excedeu 10 MB');};recorder.onerror=()=>{onError('A gravação foi interrompida');recorder.stop();};state.current={recorder,stream,timer};setSeconds(0);setRecording(true);recorder.start(250);}catch(e){onError('Não foi possível acessar o microfone para gravar.');}}
  return <button type="button" disabled={disabled} aria-label={recording?'Parar gravação':'Gravar mensagem de voz'} className={`px-2 text-sm ${recording?'text-discord-red':'text-discord-textMuted'}`} onClick={()=>recording?state.current?.recorder.stop():start()}>{recording?`⏹ ${seconds}s`:'🎙'}</button>;
}
