import {t as translate,useLocale} from '../localization';
import React,{useEffect,useState} from 'react';
import api from '../api';
import {Action,Notice} from './FormControls';
export default function NotificationSettings(){
  useLocale();
 const[settings,setSettings]=useState(null),[servers,setServers]=useState([]),[scope,setScope]=useState('default'),[id,setId]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{Promise.all([api.get('/api/settings'),api.get('/api/servers')]).then(([s,g])=>{setSettings(s.data);setServers(g.data);}).catch(()=>setError('Não foi possível carregar notificações'));},[]);
 if(!settings)return <Notice error={error} message="Carregando…"/>;
 const rules=settings.notifications,parent=scope==='channels'?rules.servers[servers.find(s=>s.channels.some(c=>c.id===id))?.id] || rules.default:rules.default,rule=scope==='default'?rules.default:rules[scope][id] || parent;
 const change=patch=>setSettings(s=>({...s,notifications:{...s.notifications,[scope]:scope==='default'?{...rule,...patch}:{...s.notifications[scope],[id]:{...rule,...patch}}}}));
 return <section className="space-y-4"><h3 className="font-semibold">{translate("Notificações por servidor e canal")}</h3><select aria-label={translate("Escopo das notificações")} value={scope} onChange={e=>{setScope(e.target.value);setId('');}} className="bg-discord-darkest rounded p-3"><option value="default">{translate("Padrão")}</option><option value="servers">{translate("Servidor")}</option><option value="channels">{translate("Canal")}</option></select>{scope!=='default'&&<select aria-label={translate("Destino das notificações")} value={id} onChange={e=>setId(e.target.value)} className="bg-discord-darkest rounded p-3 ml-2"><option value="">{translate("Escolher")}</option>{(scope==='servers'?servers:servers.flatMap(s=>s.channels.map(c=>({...c,name:s.name+' / '+c.name})))).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}<fieldset disabled={scope!=='default'&&!id} className="space-y-4"><label className="block">{translate("Receber")}<select value={rule.mode} onChange={e=>change({mode:e.target.value})} className="block bg-discord-darkest p-3 rounded w-full mt-2"><option value="all">{translate("Todas as mensagens")}</option><option value="mentions">{translate("Somente menções")}</option><option value="none">{translate("Nenhuma")}</option></select></label><label className="block">{translate("Silenciar temporariamente")}<select value={rule.mutedUntil && Date.parse(rule.mutedUntil)>Date.now()?'active':''} onChange={e=>change({mutedUntil:e.target.value?new Date(Date.now()+Number(e.target.value)*60000).toISOString():null})} className="block bg-discord-darkest p-3 rounded w-full mt-2"><option value="">{translate("Sem silêncio temporário")}</option><option value="active" disabled>{translate("Silenciado até")} {rule.mutedUntil?new Date(rule.mutedUntil).toLocaleString():''}</option><option value="15">{translate("15 minutos")}</option><option value="60">{translate("1 hora")}</option><option value="480">{translate("8 horas")}</option><option value="1440">{translate("24 horas")}</option></select></label><Action onClick={async()=>{try{const latest=(await api.get('/api/settings')).data;await api.put('/api/settings',{...latest,notifications:settings.notifications});window.dispatchEvent(new Event('social-settings-changed'));setNotice('Notificações salvas');setError('');}catch(e){setError(e.response?.data?.error || 'Falha ao salvar');}}}>{translate("Salvar notificações")}</Action>{scope!=='default'&&<Action onClick={()=>setSettings(s=>{const group={...s.notifications[scope]};delete group[id];return {...s,notifications:{...s.notifications,[scope]:group}};})}>{translate("Herdar padrão")}</Action>}</fieldset><Notice error={error} message={notice}/></section>;
}
