import {t as translate,useLocale} from '../localization';
import React,{useState} from 'react';
import {useAudioPreferences} from '../context/AudioPreferencesContext';
import {useSocial} from '../context/SocialContext';
import {useSocket} from '../context/SocketContext';
import {Modal,Action,Toggle,Notice} from './FormControls';
export default function ParticipantControls({participant:p,channel,server,onClose,onOpenProfile,onFocus,onPopOut,onPictureInPicture}) {
  useLocale();
  const{settings,participant}=useAudioPreferences(),{openDm}=useSocial(),{socket}=useSocket(),[destination,setDestination]=useState(''),[error,setError]=useState('');const pref={volume:1,muted:false,hideVideo:false,prioritizeStream:false,...settings.participants[p.user.id]},update=patch=>participant(p.user.id,patch),can=key=>channel.permissions?.[key];
  async function moderate(action,value){try{const r=await socket.timeout(10000).emitWithAck('voice_admin',{channelId:channel.id,targetSocketId:p.socketId,action,value,destinationId:destination});if(r.error)throw Error(r.error);setError('');}catch(e){setError(e.message);}}
  return <Modal title={`Na chamada · ${p.user.username}`} onClose={onClose}><div className="space-y-4"><label className="block text-sm">{translate("Volume individual:")} {Math.round(pref.volume*100)}%<input aria-label={translate("Volume individual")} type="range" min={0} max={2} step={0.05} value={pref.volume} onChange={e=>update({volume:Number(e.target.value)})} className="block w-full mt-3"/></label><Toggle label={translate("Silenciar apenas para mim")} checked={pref.muted} onChange={v=>update({muted:v})}/><Toggle label={translate("Ocultar vídeo desta pessoa")} checked={pref.hideVideo} onChange={v=>update({hideVideo:v})}/><Toggle label={translate("Priorizar transmissão desta pessoa")} checked={pref.prioritizeStream} onChange={v=>update({prioritizeStream:v})}/><div className="flex flex-wrap gap-2"><Action onClick={()=>{onOpenProfile(p.user);onClose();}}>{translate("Abrir perfil")}</Action><Action onClick={async()=>{try{await openDm(p.user);onClose();}catch(e){setError(e.response?.data?.error || 'Conversa indisponível');}}}>Enviar mensagem</Action><Action onClick={()=>{onFocus(p.socketId);onClose();}}>{translate("Focar participante")}</Action>{p.isCameraOn&&<><Action onClick={()=>onPopOut(p.socketId)}>{translate("Abrir vídeo em janela")}</Action><Action onClick={()=>onPictureInPicture(p.socketId)}>{translate("Picture-in-picture")}</Action></>}</div>{can('muteMembers')&&<Action danger onClick={()=>moderate('mute',!p.serverMuted)}>{p.serverMuted?'Remover mute do servidor':'Silenciar no servidor'}</Action>}{can('deafenMembers')&&<Action danger onClick={()=>moderate('deafen',!p.serverDeafened)}>{p.serverDeafened?'Remover deafen do servidor':'Ensurdecer no servidor'}</Action>}{can('moveMembers')&&<><select aria-label={translate("Canal de destino")} value={destination} onChange={e=>setDestination(e.target.value)} className="block bg-discord-darkest p-3 rounded w-full"><option value="">{translate("Mover para canal…")}</option>{(server?.channels || []).filter(c=>c.type==='voice' && c.id!==channel.id).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><Action disabled={!destination} onClick={()=>moderate('move')}>{translate("Mover participante")}</Action><Action danger onClick={()=>moderate('disconnect')}>{translate("Desconectar participante")}</Action></>}<Notice error={error}/></div></Modal>;
}
