import {t as translate,useLocale} from '../localization';
import React,{useState,useEffect} from 'react';
import api from '../api';
import ActivitySettings from './ActivitySettings';
import NotificationSettings from './NotificationSettings';
import {Field,Action,Notice,Toggle} from './FormControls';
import ServerProfileSettings from './ServerProfileSettings';
export default function PrivacySettings(){
  useLocale();
  const [settings,setSettings]=useState(null),[servers,setServers]=useState([]),[error,setError]=useState(''),[message,setMessage]=useState('');
  useEffect(()=>{Promise.all([api.get('/api/settings'),api.get('/api/servers')]).then(([s,g])=>{setSettings(s.data);setServers(g.data);}).catch(e=>setError(e.response?.data?.error || 'Não foi possível carregar a privacidade'));},[]);
  const change=(key,value)=>setSettings(s=>({...s,[key]:value}));
  if(!settings)return <Notice error={error} message="Carregando…"/>;
  const labels={profileVisibility:'Quem pode ver seu perfil completo',activityVisibility:'Quem pode ver sua atividade',dmPolicy:'Quem pode enviar mensagens privadas',callPolicy:'Quem pode chamar'};
  return <div className="space-y-5"><h3 className="font-bold text-lg">{translate("Privacidade e pedidos de amizade")}</h3><fieldset className="space-y-2"><legend>{translate("Permitir pedidos de")}</legend>{[['everyone','Todos'],['friendsOfFriends','Amigos de amigos'],['sharedServers','Membros de servidores em comum']].map(([key,label])=><Toggle key={key} label={translate(label)} checked={settings.friendRequests[key]} onChange={v=>change('friendRequests',{...settings.friendRequests,[key]:v})}/>)}<p className="text-xs text-discord-textMuted">{translate("Desative todas as opções para não receber pedidos.")}</p></fieldset>{Object.entries(labels).map(([key,label])=><label key={key} className="block text-sm">{translate(label)}<select value={settings[key]} onChange={e=>change(key,e.target.value)} className="block mt-2 p-3 rounded bg-discord-darkest w-full">{[['everyone','Todos'],['shared','Amigos e servidores em comum'],['friends','Somente amigos'],['none','Ninguém']].map(([v,t])=><option key={v} value={v}>{translate(t)}</option>)}</select></label>)}<Toggle label={translate("Mostrar atividade de jogos/programas")} checked={settings.allowActivity} onChange={v=>change('allowActivity',v)}/><fieldset><legend className="text-sm mb-2">{translate("Bloquear DMs de membros destes servidores")}</legend>{servers.map(s=><Toggle key={s.id} label={s.name} checked={settings.blockedDmServers.includes(s.id)} onChange={v=>change('blockedDmServers',v?[...settings.blockedDmServers,s.id]:settings.blockedDmServers.filter(id=>id!==s.id))}/>)}</fieldset><p className="text-sm text-discord-textMuted">{translate("Usuários bloqueados são gerenciados em Amigos → Bloqueados.")}</p><Action onClick={async()=>{try{const r=await api.put('/api/settings',settings);setSettings(r.data);window.dispatchEvent(new Event('social-settings-changed'));setMessage('Privacidade salva.');setError('');}catch(e){setError(e.response?.data?.error || 'Falha ao salvar');}}}>{translate("Salvar privacidade")}</Action><Notice error={error} message={message}/><NotificationSettings/><ActivitySettings/></div>;
}
export function ProfileDetails(){
  useLocale();const{currentUser,updateProfile}=useAuth();const[pronouns,setPronouns]=useState(currentUser.pronouns || ''),[statusEmoji,setEmoji]=useState(currentUser.statusEmoji || ''),[expiry,setExpiry]=useState(''),[connections,setConnections]=useState((currentUser.connections || []).map(c=>`${c.name} ${c.url}`).join('\n')),[error,setError]=useState(''),[message,setMessage]=useState('');return <div className="space-y-3"><h3 className="font-semibold">{translate("Mais informações do perfil")}</h3><Field label={translate("Pronomes")} maxLength={128} value={pronouns} onChange={e=>setPronouns(e.target.value)}/><Field label={translate("Emoji do status")} maxLength={32} value={statusEmoji} onChange={e=>setEmoji(e.target.value)}/><Field label={translate("Expiração do status (vazio: sem expiração)")} type="datetime-local" value={expiry} onChange={e=>setExpiry(e.target.value)}/><label className="block text-sm">{translate("Contas conectadas (nome e link, um por linha)")}<textarea value={connections} onChange={e=>setConnections(e.target.value)} className="block w-full mt-2 rounded p-3 bg-discord-darkest" placeholder="GitHub https://github.com/seu-usuario"/></label><Action onClick={async()=>{try{const links=connections.split('\n').filter(l=>l.trim()).map(line=>{const match=line.match(/^(.*?)\s+(https:\/\/\S+)$/);if(!match)throw Error('Use nome e link HTTPS em cada linha');return{name:match[1],url:match[2]};});await api.put('/api/profile/details',{pronouns,statusEmoji,statusExpires:expiry?new Date(expiry).toISOString():null,connections:links,activity:currentUser.activity});await updateProfile({});setMessage('Informações salvas.');setError('');}catch(e){setError(e.response?.data?.error || e.message);}}}>{translate("Salvar informações")}</Action><Notice error={error} message={message}/><ServerProfileSettings/></div>;}
import {useAuth} from '../context/AuthContext';
