import {t as translate,useLocale} from '../localization';
import React,{useState,useEffect} from 'react';
import {useSocial} from '../context/SocialContext';
import {useVoice} from '../context/VoiceContext';
import {useSocket} from '../context/SocketContext';
import VoiceRoom from './VoiceRoom';
import api from '../api';
import {History,ChevronDown} from 'lucide-react';
export function PrivateCallNotice(){
  useLocale();const{incomingCall,activeCall,respondCall,endCall,error}=useSocial();const[now,setNow]=useState(Date.now());useEffect(()=>{if(!activeCall)return;setNow(Date.now());const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[activeCall?.id]);const start=activeCall?.answered_at || activeCall?.started_at,seconds=start?Math.max(0,Math.floor((now-Date.parse(start))/1000)):0;return <>{incomingCall&&<section role="alertdialog" aria-label={translate("Chamada recebida")} className="fixed top-4 right-4 z-[80] max-w-sm bg-discord-darker text-discord-textNormal shadow-xl rounded-xl p-5 border border-discord-blurple"><h3 className="font-bold">{incomingCall.caller?.username || 'Um amigo'} {translate("está chamando")}</h3><p className="text-sm mb-3">{incomingCall.video?translate("Chamada de vídeo"):translate("Chamada de áudio")}</p><div className="flex gap-3 text-sm"><button onClick={()=>respondCall('accept')} className="bg-discord-green text-white px-3 py-2 rounded">{translate("Atender")}</button><button onClick={()=>respondCall('decline')} className="bg-discord-red text-white px-3 py-2 rounded">{translate("Recusar")}</button><button onClick={()=>respondCall('ignore')}>{translate("Ignorar")}</button></div>{error&&<p className="text-discord-red text-xs mt-2">{error}</p>}</section>}{activeCall&&<div className="fixed bottom-2 left-1/2 -translate-x-1/2 z-30 bg-discord-darker px-4 py-2 rounded-full text-xs flex gap-3 shadow-lg"><span>{activeCall.state==='ringing'?'Chamando…':`Chamada · ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`}</span><button className="text-discord-red" onClick={endCall}>{translate("Encerrar chamada")}</button></div>}</>;}
export function PrivateCallRoom({conversationId,onOpenProfile}){
  useLocale();const{currentVoiceChannel}=useVoice();if(!currentVoiceChannel?.isPrivateCall || currentVoiceChannel.conversationId!==conversationId)return null;return <div className="h-[46vh] min-h-64 shrink-0 border-b border-discord-active"><VoiceRoom channel={currentVoiceChannel} onOpenProfile={onOpenProfile}/></div>;}
export function CallHistory({conversationId}){
  useLocale();const{socket}=useSocket();const[records,setRecords]=useState([]),[open,setOpen]=useState(false);useEffect(()=>{const refresh=()=>api.get(`/api/dms/${conversationId}/calls`).then(r=>setRecords(r.data)).catch(()=>{});refresh();socket?.on('private_call_invitation',refresh);socket?.on('private_call_ended',refresh);return()=>{socket?.off('private_call_invitation',refresh);socket?.off('private_call_ended',refresh);};},[conversationId,socket]);return <div className="call-history"><button type="button" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><History size={15}/>{translate("Histórico de chamadas (")}{records.length})<ChevronDown size={14}/></button>{open&&<div className="call-history-records">{records.map(r=><p key={r.id}>{['missed','declined'].includes(r.state)?'📞 Chamada perdida':'📞'} · {r.username} {translate("iniciou uma chamada ·")} {new Date(r.started_at).toLocaleString()}{r.ended_at?` · ${Math.max(0,Math.round((Date.parse(r.ended_at)-Date.parse(r.answered_at || r.started_at))/1000))}s`:''}</p>)}</div>}</div>;}
