import {t as translate,useLocale} from '../localization';
import React,{useState,useEffect} from 'react';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import api from '../api';
import {usePreferences} from '../context/PreferencesContext';
import ProtectedImage,{useProtectedSource,downloadAttachment} from './ProtectedImage';

function discordSyntax(){return(tree,file)=>{function visit(node){if(node.type==='strong' && file.value.slice(node.position?.start.offset,node.position?.start.offset+2)==='__')node.data={hName:'u'};if(!node.children)return;node.children=node.children.flatMap(child=>{if(child.type!=='text')return child;const parts=[],regex=/\|\|([^|]+)\|\||<@&([\w:-]+)>|<@([\w:-]+)>|<#([\w:-]+)>|@(?:everyone|here|[\w.-]+)|#[\w-]+/g;let last=0;for(const match of child.value.matchAll(regex)){if(match.index>last)parts.push({type:'text',value:child.value.slice(last,match.index)});parts.push({type:'text',value:match[1] || match[0],data:{hName:'span',hProperties:{className:match[1]?'spoiler':'mention','data-user':match[3] || undefined,'data-channel':match[4] || undefined,'data-role':match[2] || undefined}}});last=match.index+match[0].length;}if(last<child.value.length)parts.push({type:'text',value:child.value.slice(last)});return parts.length?parts:child;});node.children.forEach(visit);}visit(tree);};}
function Spoiler({children}){
  useLocale();const[shown,setShown]=useState(false);return <button type="button" className={`rounded px-1 ${shown?'bg-discord-active':'bg-discord-darkest text-transparent'}`} aria-label={shown?'Ocultar spoiler':'Mostrar spoiler'} onClick={()=>setShown(v=>!v)}>{children}</button>;}
const safeLink=href=>/^https?:\/\//i.test(href || '')?href:'';
export default function RichMessage({content='',editedAt}){
  useLocale();const{preferences}=usePreferences(),parts=String(content).split(/(\[\[sticker:[\w-]+\]\]|<:[^:>]+:[\w-]+>)/g);const components={a:({href,children})=><a href={safeLink(href)} target="_blank" rel="noopener noreferrer" className="text-discord-blurple underline">{children}</a>,img:({src,alt})=><span className="text-discord-textMuted">{alt || 'Imagem externa'} <a href={safeLink(src)} target="_blank" rel="noopener noreferrer">{translate("Abrir")}</a></span>,code:({children})=><code className="bg-discord-darkest px-1 rounded font-mono text-[.9em]">{children}</code>,pre:({children})=><pre className="bg-discord-darkest p-3 rounded overflow-auto whitespace-pre-wrap">{children}</pre>,blockquote:({children})=><blockquote className="border-l-4 border-discord-textMuted pl-3 text-discord-textMuted">{children}</blockquote>,span:({className,children,...props})=>className==='spoiler'?<Spoiler>{children}</Spoiler>:className==='mention'?<Mention type={props['data-channel']?'channel':props['data-role']?'role':'user'} id={props['data-channel'] || props['data-role'] || props['data-user']} text={children}/>:<span className={className}>{children}</span>};return <div className="message-content rich-message break-words select-text">{parts.map((p,i)=>p.startsWith('<:')?<CustomAsset key={i} id={p.match(/:([\w:-]+)>$/)?.[1]} emoji/>:p.startsWith('[[sticker:') && !['[[sticker:party]]','[[sticker:wave]]','[[sticker:heart]]'].includes(p)?<CustomAsset key={i} id={p.slice(10,-2)}/>:p.startsWith('[[sticker:')?<span key={i} className="text-6xl block py-2" role="img" aria-label="Sticker">{{'[[sticker:party]]':'🎉','[[sticker:wave]]':'👋','[[sticker:heart]]':'💖'}[p]}</span>:<Markdown key={i} remarkPlugins={[remarkGfm,discordSyntax]} components={components} skipHtml>{p}</Markdown>)}{editedAt&&<span className="text-[10px] text-discord-textMuted">{translate("(editada)")}</span>}{preferences.linkPreviews&&[...new Set(content.match(/https:\/\/[^\s<>]+/g) || [])].slice(0,2).map(url=><LinkPreview key={url} url={url}/>)}</div>;}
function LinkPreview({url}){
  useLocale();const[preview,setPreview]=useState(null);useEffect(()=>{let alive=true;api.get('/api/link-preview',{params:{url}}).then(r=>{if(alive)setPreview(r.data);}).catch(()=>{});return()=>{alive=false;};},[url]);return preview?<a href={safeLink(preview.url)} target="_blank" rel="noopener noreferrer" className="block bg-discord-darker border-l-4 border-discord-blurple rounded p-3 my-2 max-w-md"><small className="text-discord-textMuted">{preview.site}</small><b className="block text-discord-blurple">{preview.title}</b><p className="text-xs mt-1">{preview.description}</p></a>:null;}
export function Attachment({attachment,onError=()=>{}}){
  useLocale();const src=useProtectedSource(attachment?.url),{preferences}=usePreferences(),[animate,setAnimate]=useState(false);if(!attachment)return null;const type=attachment.mimetype || '';return <div className="my-2 max-w-md bg-discord-darker rounded p-2">{type.startsWith('image/')?type==='image/gif' && (!preferences.showGifs || !preferences.autoPlayGifs) && !animate?<button type="button" onClick={()=>setAnimate(true)} className="p-4 text-sm">{translate("▶ Mostrar GIF:")} {attachment.filename}</button>:<ProtectedImage src={attachment.url} alt={attachment.filename} className="max-h-80 rounded object-contain"/>:type.startsWith('video/')?<video src={src} controls preload="metadata" className="w-full max-h-80 rounded"/>:type.startsWith('audio/')?<audio src={src} controls preload="metadata" className="w-full"/>:null}<div className="flex gap-3 items-center mt-2 text-xs"><span className="truncate flex-1">{attachment.filename}</span><button type="button" onClick={()=>downloadAttachment(attachment.url,attachment.filename).catch(()=>onError('Falha ao baixar arquivo'))} className="text-discord-blurple">{translate("Baixar")}</button></div></div>;}

export function CustomAsset({id,emoji=false}){
  useLocale();const[asset,setAsset]=useState(null);useEffect(()=>{let alive=true;api.get(`/api/assets/${id}`).then(r=>{if(alive)setAsset(r.data);}).catch(()=>{});return()=>{alive=false;};},[id]);return asset?<ProtectedImage src={asset.url} alt={asset.name} title={asset.name} className={emoji?"inline w-6 h-6 object-contain align-middle":"w-36 h-36 object-contain block"}/>:<span className="text-discord-textMuted text-xs">{translate("Mídia indisponível")}</span>;}

function Mention({type,id,text}){
  useLocale();const [resolved,setResolved]=useState(null);const raw=Array.isArray(text)?text.join(''):String(text || ''),lookup=id || (raw.startsWith('@')?raw.slice(1):null);useEffect(()=>{if(!lookup || ['here','everyone'].includes(lookup))return;let alive=true;api.get('/api/mentions/resolve',{params:{type,id:lookup}}).then(r=>{if(alive)setResolved(r.data);}).catch(()=>{});return()=>{alive=false;};},[type,lookup]);return <button type="button" className="mention" onClick={()=>{if(!resolved)return;if(type==='user')window.dispatchEvent(new CustomEvent('open-user-profile',{detail:resolved}));if(type==='channel')window.dispatchEvent(new CustomEvent('navigate-channel',{detail:resolved}));}}>{resolved?(type==='channel'?'#':'@')+resolved.name:raw}</button>;}
