import {t as translate,useLocale} from '../localization';
import React,{useState,useEffect} from 'react';
import api from '../api';
import {useSocket} from '../context/SocketContext';
import {useAuth} from '../context/AuthContext';
import {Modal,Field,Action,Notice,Toggle} from './FormControls';
import ProtectedImage from './ProtectedImage';

export const PERMISSION_LABELS={administrator:'Administrador',manageServer:'Gerenciar servidor',manageChannels:'Gerenciar canais',manageRoles:'Gerenciar cargos',kickMembers:'Expulsar membros',banMembers:'Banir membros',manageNicknames:'Gerenciar apelidos',changeNickname:'Alterar próprio apelido',createInvite:'Criar convites',viewChannel:'Ver canal',sendMessages:'Enviar mensagens',readHistory:'Ver histórico',manageMessages:'Gerenciar mensagens',pinMessages:'Fixar mensagens',attachFiles:'Anexar arquivos',embedLinks:'Enviar links',addReactions:'Reagir',useGifs:'Enviar GIFs',useExternalEmoji:'Emojis externos',mentionUsers:'Mencionar usuários',mentionEveryone:'Mencionar todos',useCommands:'Usar comandos',createThreads:'Criar threads',manageThreads:'Gerenciar threads',connect:'Entrar em voz',speak:'Falar',video:'Transmitir câmera',stream:'Compartilhar tela',muteMembers:'Silenciar membros',deafenMembers:'Ensurdecer membros',moveMembers:'Mover membros',manageAssets:'Gerenciar emojis, stickers e sons',manageEvents:'Gerenciar eventos',viewAudit:'Ver registro administrativo',useSoundboard:'Usar soundboard'};
export default function ServerManagement({server,onClose,onOpenProfile}) {
  useLocale();
  const {socket}=useSocket(),{currentUser}=useAuth();const [data,setData]=useState(null),[tab,setTab]=useState('server'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  async function refresh(){const r=await api.get(`/api/servers/${server.id}/community`);setData(r.data);}
  useEffect(()=>{refresh().catch(e=>setError(e.response?.data?.error || 'Não foi possível carregar o servidor'));const update=s=>{if(s.id===server.id)refresh().catch(()=>{});};socket?.on('server_updated',update);return()=>socket?.off('server_updated',update);},[server.id,socket]);
  async function run(fn,message='Alterações salvas'){setBusy(true);setError('');setNotice('');try{await fn();await refresh();setNotice(message);}catch(e){setError(e.response?.data?.error || 'Não foi possível concluir a alteração');}finally{setBusy(false);}}
  const permissions=data?.server.permissions || {},can=name=>!!permissions[name],base=`/api/servers/${server.id}`;
  const highest=Math.max(0,...(data?.members.find(m=>m.id===currentUser.id)?.roles || []).map(r=>r.position)),canEditRole=r=>can('manageRoles') && (data?.server.owner_id===currentUser.id || r.position<highest);
  return <Modal title={`Servidor · ${server.name}`} onClose={onClose} wide><nav className="flex flex-wrap gap-2 border-b border-discord-active pb-3 mb-4">{Object.entries({server:'Visão geral',channels:'Canais e categorias',roles:'Cargos',permissions:'Permissões',members:'Membros',events:'Eventos',assets:'Emojis e mídia',bans:'Banimentos',audit:'Registro administrativo'}).filter(([t])=>t!=='bans' || can('banMembers')).filter(([t])=>t!=='audit' || can('viewAudit')).map(([t,label])=><button type="button" key={translate(t)} onClick={()=>setTab(t)} className={`rounded p-2 text-sm ${t===tab?'bg-discord-blurple text-white':'bg-discord-darker'}`}>{translate(label)}</button>)}</nav><Notice error={error} message={notice}/>{!data?<p>{translate("Carregando…")}</p>:<div className="space-y-5">
    {tab==='server'&&<ServerOverview server={data.server} currentUser={currentUser} can={can} busy={busy} run={run} base={base} members={data.members} onClose={onClose}/>}
    {tab==='channels'&&<><h3 className="font-semibold">{translate("Categorias")}</h3>{data.server.categories.map(c=><CategoryEditor key={c.id} category={c} categories={data.server.categories} enabled={can('manageChannels')} run={run} base={base}/>)}{can('manageChannels')&&<CreateName label={translate("Nova categoria")} busy={busy} onCreate={name=>run(()=>api.post(`${base}/categories`,{name}))}/>}<h3 className="font-semibold">{translate("Canais")}</h3>{data.server.channels.map(c=><OrderedItem key={c.id} id={c.id} kind="channels" rows={data.server.channels} enabled={can('manageChannels')} run={run} base={base}><ChannelEditor channel={c} categories={data.server.categories} enabled={can('manageChannels')} run={run} base={base}/></OrderedItem>)}{can('manageChannels')&&<CreateChannel run={run} base={base}/>}</>}
    {tab==='roles'&&<>{data.roles.map(r=><OrderedItem key={r.id} id={r.id} kind="roles" rows={data.roles.filter(r=>!r.is_default && canEditRole(r))} enabled={canEditRole(r)&&!r.is_default} run={run} base={base}><RoleEditor role={r} names={data.permissions} enabled={canEditRole(r)} run={run} base={base}/></OrderedItem>)}{can('manageRoles')&&<CreateName label={translate("Novo cargo")} busy={busy} onCreate={name=>run(()=>api.post(`${base}/roles`,{name}))}/>}</>}
    {tab==='permissions'&&(can('manageRoles')?<OverrideEditor base={base} data={data} run={run}/>:<p>{translate("Você não tem permissão para alterar permissões.")}</p>)}
    {tab==='members'&&<MemberManager data={data} base={base} can={can} run={run} onOpenProfile={onOpenProfile} currentUser={currentUser}/>}
    {tab==='events'&&<EventManager serverId={server.id} channels={data.server.channels} canManage={can('manageEvents')} run={run} currentUser={currentUser}/>}
    {tab==='assets'&&<AssetManager serverId={server.id} canManage={can('manageAssets')} run={run}/>}
    {tab==='bans'&&<ReadRecords url={`${base}/bans`} render={r=><div className="flex gap-3 items-center p-3 rounded bg-discord-darker"><span className="flex-1">{r.username}<small className="block text-discord-textMuted">{r.reason}</small></span><Action onClick={()=>run(()=>api.delete(`${base}/bans/${r.user_id}`))}>{translate("Remover banimento")}</Action></div>}/>}
    {tab==='audit'&&<ReadRecords url={`${base}/audit`} render={r=><div className="p-3 rounded bg-discord-darker text-sm"><b>{r.username || translate("Conta")}</b> · {auditLabel(r.action)}<time className="block text-xs text-discord-textMuted">{new Date(r.created_at).toLocaleString()}</time></div>}/>}
  </div>}</Modal>;
}
function OrderedItem({id,kind,rows,enabled,run,base,children}){
  useLocale();return <div draggable={enabled} onDragStart={e=>e.dataTransfer.setData(`application/meuapp-${kind}`,id)} onDragOver={e=>{if(enabled)e.preventDefault();}} onDrop={e=>{e.preventDefault();if(!enabled)return;const from=e.dataTransfer.getData(`application/meuapp-${kind}`);if(!from || from===id || !rows.some(r=>r.id===from))return;const ids=rows.filter(r=>r.id!==from).map(r=>r.id);ids.splice(ids.indexOf(id),0,from);run(()=>api.put(`${base}/order`,{kind,ids:kind==='roles'?ids.reverse():ids}));}}>{children}</div>;}
const auditLabel=action=>({server:'Servidor',channel:'Canal',category:'Categoria',role:'Cargo',member:'Membro',invite:'Convite',permissions:'Permissões',asset:'Mídia',event:'Evento',roles:'Cargos',channels:'Canais',categories:'Categorias'}[action.split('.')[0]] || action.split('.')[0])+' · '+({create:'criado',update:'alterado',delete:'excluído',transfer:'propriedade transferida',reorder:'ordem alterada',leave:'saiu',kick:'expulso',ban:'banido',unban:'banimento removido',timeout:'silenciamento temporário'}[action.split('.')[1]] || action.split('.')[1]);
function CreateName({label,onCreate,busy}){
  useLocale();const[name,setName]=useState('');return <form className="flex gap-2" onSubmit={e=>{e.preventDefault();onCreate(name);setName('');}}><input aria-label={translate(label)} required maxLength={100} value={name} onChange={e=>setName(e.target.value)} className="flex-1 bg-discord-darkest rounded p-3" placeholder={translate(label)}/><Action type="submit" disabled={busy || !name.trim()}>{translate("Criar")}</Action></form>;}
function ServerOverview({server,currentUser,can,busy,run,base,members,onClose}){
  useLocale();const[name,setName]=useState(server.name),[description,setDescription]=useState(server.description || ''),[icon,setIcon]=useState(server.icon || ''),[banner,setBanner]=useState(server.banner || ''),[target,setTarget]=useState('');async function image(file,set){if(!file)return;const form=new FormData();form.append('file',file);await run(async()=>set((await api.post('/api/upload',form)).data.url),'Imagem carregada; salve o servidor para aplicar.');}return <div className="space-y-4"><Field label={translate("Nome do servidor")} value={name} onChange={e=>setName(e.target.value)} disabled={!can('manageServer')}/><Field label={translate("Descrição")} value={description} maxLength={1000} onChange={e=>setDescription(e.target.value)} disabled={!can('manageServer')}/><Field label={translate("Ícone (emoji ou imagem)")} value={icon} onChange={e=>setIcon(e.target.value)} disabled={!can('manageServer')}/>{icon.startsWith('/uploads/')&&<ProtectedImage src={icon} alt="Ícone" className="w-16 h-16 rounded-full"/>}{can('manageServer')&&<label className="block text-sm">{translate("Carregar ícone")}<input type="file" accept="image/*" onChange={e=>image(e.target.files[0],setIcon)} className="block mt-2"/></label>}<Field label={translate("Banner")} value={banner} onChange={e=>setBanner(e.target.value)} disabled={!can('manageServer')}/>{can('manageServer')&&<><label className="block text-sm">{translate("Carregar banner")}<input type="file" accept="image/*" onChange={e=>image(e.target.files[0],setBanner)} className="block mt-2"/></label><Action disabled={busy} onClick={()=>run(()=>api.patch(`${base}/details`,{name,description,icon,banner}))}>{translate("Salvar servidor")}</Action></>}{server.owner_id===currentUser.id?<div className="space-y-3 pt-5 border-t border-discord-active"><label className="text-sm">{translate("Transferir propriedade")}<select value={target} onChange={e=>setTarget(e.target.value)} className="block bg-discord-darkest p-3 rounded w-full mt-2"><option value="">{translate("Escolher membro")}</option>{members.filter(m=>m.id!==currentUser.id).map(m=><option key={m.id} value={m.id}>{m.username}</option>)}</select></label><Action disabled={!target || busy} onClick={()=>{if(window.confirm('Transferir a propriedade para o membro escolhido?'))run(()=>api.post(`${base}/transfer`,{userId:target}));}}>{translate("Transferir")}</Action><Action danger disabled={busy} onClick={()=>{if(window.confirm('Excluir este servidor? Ele deixará de aparecer para todos os membros.'))run(async()=>{await api.delete(base);onClose();});}}>{translate("Excluir servidor")}</Action></div>:<Action danger onClick={()=>{if(window.confirm('Sair deste servidor?'))run(async()=>{await api.post(`${base}/leave`);onClose();});}}>{translate("Sair do servidor")}</Action>}</div>;}
function CategoryEditor({category,categories,enabled,run,base}){
  useLocale();const[name,setName]=useState(category.name),[position,setPosition]=useState(category.position);return <div draggable={enabled} onDragStart={e=>e.dataTransfer.setData('application/meuapp-category',category.id)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('application/meuapp-category');if(enabled && id && id!==category.id){const ids=categories.filter(c=>c.id!==id).map(c=>c.id);ids.splice(ids.indexOf(category.id),0,id);run(()=>api.put(`${base}/order`,{kind:'categories',ids}));}}} className="flex flex-wrap gap-2 items-center bg-discord-darker p-3 rounded"><input aria-label={translate("Nome da categoria")} value={name} onChange={e=>setName(e.target.value)} disabled={!enabled} className="bg-discord-darkest p-2 rounded flex-1"/><input aria-label={translate("Posição da categoria")} type="number" min={0} value={position} onChange={e=>setPosition(Number(e.target.value))} disabled={!enabled} className="bg-discord-darkest p-2 rounded w-20"/>{enabled&&<><Action onClick={()=>run(()=>api.patch(`${base}/categories/${category.id}`,{name,position}))}>{translate("Salvar")}</Action><Action danger onClick={()=>{if(window.confirm('Excluir a categoria? Os canais serão mantidos.'))run(()=>api.delete(`${base}/categories/${category.id}`));}}>{translate("Excluir")}</Action></>}</div>;}
function CreateChannel({run,base}){
  useLocale();const[name,setName]=useState(''),[type,setType]=useState('text'),[topic,setTopic]=useState('');return <div className="space-y-2"><Field label={translate("Novo canal")} value={name} onChange={e=>setName(e.target.value)}/><select aria-label={translate("Tipo do novo canal")} value={type} onChange={e=>setType(e.target.value)} className="bg-discord-darkest p-2 rounded"><option value="text">{translate("Texto")}</option><option value="voice">{translate("Voz")}</option></select><Field label={translate("Tópico do novo canal")} value={topic} onChange={e=>setTopic(e.target.value)}/><Action disabled={!name.trim()} onClick={()=>run(async()=>{await api.post(`${base}/channels`,{name,type,topic});setName('');})}>{translate("Criar canal")}</Action></div>;}
function ChannelEditor({channel,categories,enabled,run,base}){
  useLocale();const[value,setValue]=useState(channel),patch=(key,value)=>setValue(s=>({...s,[key]:value}));return <details className="bg-discord-darker p-3 rounded"><summary className="cursor-pointer font-semibold">{channel.type==='voice'?'🔊':'#'} {channel.name}</summary><div className="grid grid-cols-2 gap-3 mt-3"><Field label={translate("Nome")} value={value.name} onChange={e=>patch('name',e.target.value)} disabled={!enabled}/><Field label={translate("Tópico / descrição")} value={value.topic} onChange={e=>patch('topic',e.target.value)} disabled={!enabled}/><label className="text-sm">{translate("Categoria")}<select value={value.category_id || ''} onChange={e=>patch('category_id',e.target.value)} disabled={!enabled} className="bg-discord-darkest block w-full p-3 rounded mt-2"><option value="">{translate("Sem categoria")}</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><Field label={translate("Posição")} type="number" min={0} value={value.position} onChange={e=>patch('position',Number(e.target.value))} disabled={!enabled}/>{channel.type==='text'?<Field label={translate("Modo lento (segundos)")} type="number" min={0} max={21600} value={value.slowmode} onChange={e=>patch('slowmode',Number(e.target.value))} disabled={!enabled}/>:<Field label={translate("Limite de usuários (0: sem limite)")} type="number" min={0} max={1000} value={value.user_limit} onChange={e=>patch('user_limit',Number(e.target.value))} disabled={!enabled}/>}<Toggle label={translate("Sincronizar permissões com a categoria")} checked={value.permission_sync} onChange={v=>patch('permission_sync',v?1:0)}/><Toggle label={translate("Conteúdo restrito a adultos")} checked={value.nsfw} onChange={v=>patch('nsfw',v?1:0)}/></div>{enabled&&<div className="flex gap-3 mt-3"><Action onClick={()=>run(()=>api.patch(`${base}/channels/${channel.id}`,value))}>{translate("Salvar canal")}</Action><Action danger onClick={()=>{if(window.confirm('Excluir o canal? O histórico será preservado.'))run(()=>api.delete(`${base}/channels/${channel.id}`));}}>{translate("Excluir canal")}</Action></div>}</details>;}
function RoleEditor({role,names,enabled,run,base}){
  useLocale();const[value,setValue]=useState({...role,permissions:typeof role.permissions==='string'?JSON.parse(role.permissions):role.permissions}),patch=(key,value)=>setValue(s=>({...s,[key]:value}));return <details className="bg-discord-darker p-3 rounded"><summary className="cursor-pointer font-semibold" style={{color:role.color}}>{role.name} {translate("· posição")} {role.position}</summary><div className="grid grid-cols-2 gap-3 mt-3"><Field label={translate("Nome do cargo")} value={value.name} disabled={!enabled || role.is_default} onChange={e=>patch('name',e.target.value)}/><Field label={translate("Cor do cargo")} type="color" value={value.color} disabled={!enabled} onChange={e=>patch('color',e.target.value)}/><Field label={translate("Hierarquia")} type="number" min={0} value={value.position} disabled={!enabled || role.is_default} onChange={e=>patch('position',Number(e.target.value))}/><Toggle label={translate("Mostrar membros deste cargo separadamente")} checked={value.hoist} onChange={v=>patch('hoist',v?1:0)}/></div><fieldset disabled={!enabled} className="grid grid-cols-2 gap-1 my-4">{names.map(name=><Toggle key={name} label={PERMISSION_LABELS[name] || name} checked={value.permissions[name]} onChange={v=>patch('permissions',{...value.permissions,[name]:v})}/>)}</fieldset>{enabled&&<div className="flex gap-2"><Action onClick={()=>run(()=>api.put(`${base}/roles/${role.id}`,value))}>{translate("Salvar cargo")}</Action>{!role.is_default&&<Action danger onClick={()=>{if(window.confirm('Remover este cargo de todos os membros?'))run(()=>api.delete(`${base}/roles/${role.id}`));}}>{translate("Remover cargo")}</Action>}</div>}</details>;}
function OverrideEditor({base,data,run}){
  useLocale();const[kind,setKind]=useState('channel'),[scope,setScope]=useState(''),[role,setRole]=useState(data.roles.find(r=>r.is_default)?.id || ''),[decisions,setDecisions]=useState({});useEffect(()=>{api.get(`${base}/overrides`).then(r=>setDecisions(Object.fromEntries(r.data.filter(o=>o.scope_kind===kind && o.scope_id===scope && o.role_id===role).map(o=>[o.permission,o.decision])))).catch(()=>{});},[kind,scope,role]);return <div className="space-y-4"><p className="text-sm">{translate("Permitir e negar substituem os cargos neste canal. Herança usa as permissões do servidor. Canais sincronizados usam as permissões da categoria.")}</p><select aria-label={translate("Escopo das permissões")} value={kind} onChange={e=>{setKind(e.target.value);setScope('');}} className="bg-discord-darkest p-3 rounded"><option value="channel">{translate("Canal")}</option><option value="category">{translate("Categoria")}</option></select><select aria-label={translate("Canal ou categoria")} value={scope} onChange={e=>setScope(e.target.value)} className="bg-discord-darkest p-3 rounded ml-2"><option value="">{translate("Escolher")}</option>{(kind==='channel'?data.server.channels:data.server.categories).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select aria-label={translate("Cargo das permissões")} value={role} onChange={e=>setRole(e.target.value)} className="bg-discord-darkest p-3 rounded ml-2">{data.roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><div className="grid grid-cols-2 gap-3">{(data.channelPermissions || []).map(name=><label key={name} className="text-sm">{PERMISSION_LABELS[name]}<select value={decisions[name]??-1} onChange={e=>setDecisions(s=>({...s,[name]:Number(e.target.value)}))} className="block bg-discord-darkest p-2 rounded w-full mt-1"><option value={-1}>{translate("Herdar")}</option><option value={0}>{translate("Negar")}</option><option value={1}>{translate("Permitir")}</option></select></label>)}</div><Action disabled={!scope || !role} onClick={()=>run(()=>api.put(`${base}/overrides`,{scopeKind:kind,scopeId:scope,roleId:role,decisions}))}>{translate("Salvar permissões")}</Action></div>;}
function MemberManager({data,base,can,run,onOpenProfile,currentUser}){
  useLocale();const[search,setSearch]=useState('');return <div className="space-y-3"><Field label={translate("Pesquisar membro")} value={search} onChange={e=>setSearch(e.target.value)}/>{data.members.filter(m=>`${m.username} ${m.handle} ${m.nickname}`.toLowerCase().includes(search.toLowerCase())).map(m=><details key={m.id} className="bg-discord-darker p-3 rounded"><summary className="cursor-pointer">{m.nickname || m.username} · @{m.handle} · {m.status==='offline'?translate("Offline"):translate("Online")}</summary><div className="flex flex-wrap gap-2 my-3"><Action onClick={()=>onOpenProfile(m)}>{translate("Abrir perfil")}</Action>{(m.id===currentUser.id?can('changeNickname'):can('manageNicknames'))&&<Action onClick={()=>{const nickname=window.prompt('Apelido neste servidor',m.nickname || '');if(nickname!==null)run(()=>api.put(`${base}/members/${m.id}`,{nickname}));}}>{translate("Alterar apelido")}</Action>}{can('manageRoles')&&m.id!==currentUser.id&&<label className="text-sm block w-full">{translate("Cargos")}<select aria-label={`Cargos de ${m.username}`} multiple value={m.roles.filter(r=>!r.is_default).map(r=>r.id)} onChange={e=>run(()=>api.put(`${base}/members/${m.id}`,{roles:[...e.target.selectedOptions].map(o=>o.value)}))} className="block bg-discord-darkest p-3 rounded mt-2">{data.roles.filter(r=>!r.is_default).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>}{[['kick','Expulsar','kickMembers'],['ban','Banir','banMembers'],['timeout','Silenciar temporariamente','muteMembers']].filter(([,label,p])=>can(p) && m.id!==currentUser.id).map(([action,label])=><Action key={action} danger onClick={()=>{const reason=window.prompt(`${label}: motivo`);if(reason!==null)run(()=>api.post(`${base}/members/${m.id}/${action}`,{reason,seconds:600}));}}>{translate(label)}</Action>)}{m.timeoutUntil&&can('muteMembers')&&<Action onClick={()=>run(()=>api.post(`${base}/members/${m.id}/timeout`,{seconds:0}))}>{translate("Remover silenciamento")}</Action>}</div></details>)}</div>;}
function ReadRecords({url,render}){
  useLocale();const[rows,setRows]=useState([]),[error,setError]=useState('');const refresh=()=>api.get(url).then(r=>setRows(r.data)).catch(e=>setError(e.response?.data?.error || 'Não foi possível carregar'));useEffect(()=>{refresh();},[url]);return <div className="space-y-2"><Action onClick={refresh}>{translate("Atualizar")}</Action><Notice error={error}/>{!rows.length&&<p>{translate("Nenhum registro.")}</p>}{rows.map((r,i)=><React.Fragment key={r.id || r.user_id || i}>{render(r)}</React.Fragment>)}</div>;}
export function EventManager({serverId,channels,canManage,run,currentUser}){
  useLocale();const[rows,setRows]=useState([]),[name,setName]=useState(''),[description,setDescription]=useState(''),[startsAt,setStart]=useState(''),[channelId,setChannel]=useState('');const{socket}=useSocket();const refresh=()=>api.get(`/api/servers/${serverId}/events`).then(r=>setRows(r.data));useEffect(()=>{refresh().catch(()=>{});socket?.on('events_changed',refresh);return()=>socket?.off('events_changed',refresh);},[serverId,socket]);return <div className="space-y-4">{rows.map(e=><div key={e.id} className="bg-discord-darker p-4 rounded"><h4 className="font-semibold">{e.name}</h4><p className="text-sm">{e.description}</p><time className="block text-sm my-2">{new Date(e.starts_at).toLocaleString()}</time><p className="text-xs mb-2">{e.interests.length} {translate("interessados ·")} {channels.find(c=>c.id===e.channel_id)?.name || translate("Sem canal")}</p><Action onClick={()=>run(async()=>{await api.put(`/api/events/${e.id}/interest`,{interested:!e.interests.some(i=>i.user_id===currentUser.id)});await refresh();})}>{e.interests.some(i=>i.user_id===currentUser.id)?translate("Remover interesse"):translate("Tenho interesse / lembrar")}</Action>{canManage&&<Action danger onClick={()=>{if(window.confirm('Cancelar este evento?'))run(async()=>{await api.delete(`/api/events/${e.id}`);await refresh();});}}>{translate("Cancelar evento")}</Action>}</div>)}{canManage&&<div className="space-y-3"><Field label={translate("Nome do evento")} value={name} onChange={e=>setName(e.target.value)}/><Field label={translate("Descrição")} value={description} onChange={e=>setDescription(e.target.value)}/><Field label={translate("Data e hora")} type="datetime-local" value={startsAt} onChange={e=>setStart(e.target.value)}/><select value={channelId} onChange={e=>setChannel(e.target.value)} aria-label={translate("Canal do evento")} className="bg-discord-darkest p-3 rounded"><option value="">{translate("Sem canal")}</option>{channels.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><Action disabled={!name.trim() || !startsAt} onClick={()=>run(async()=>{await api.post(`/api/servers/${serverId}/events`,{name,description,startsAt:new Date(startsAt).toISOString(),channelId});await refresh();setName('');})}>{translate("Criar evento")}</Action></div>}</div>;}
export function AssetManager({serverId,canManage=true,run}){
  useLocale();const[kind,setKind]=useState('emoji'),[rows,setRows]=useState([]),[name,setName]=useState(''),[file,setFile]=useState(null);const refresh=()=>api.get('/api/assets',{params:{kind,serverId}}).then(r=>setRows(r.data));useEffect(()=>{refresh().catch(()=>{});},[kind,serverId]);return <div className="space-y-3"><select aria-label={translate("Tipo de mídia")} value={kind} onChange={e=>setKind(e.target.value)} className="bg-discord-darkest p-3 rounded">{[['emoji','Emojis'],['sticker','Stickers'],['gif','GIFs'],['sound','Sons']].map(([v,t])=><option key={v} value={v}>{translate(t)}</option>)}</select><div className="grid grid-cols-4 gap-3">{rows.map(a=><div key={a.id} className="bg-discord-darker p-3 rounded text-center">{kind==='sound'?<p>🎵</p>:<ProtectedImage src={a.url} alt={a.name} className="w-14 h-14 object-contain mx-auto"/>}<p className="text-xs mt-2">{a.name}</p>{canManage&&<button onClick={()=>run(async()=>{await api.delete(`/api/assets/${a.id}`);await refresh();})} className="text-discord-red text-xs">{translate("Remover")}</button>}</div>)}</div>{canManage&&<><Field label={translate("Nome da mídia")} value={name} onChange={e=>setName(e.target.value)}/><input aria-label={translate("Arquivo da mídia")} type="file" accept={kind==='sound'?'audio/*':kind==='gif'?'image/gif':'image/*'} onChange={e=>setFile(e.target.files[0])}/><Action disabled={!file || !name.trim()} onClick={()=>run(async()=>{const form=new FormData();form.append('file',file);const upload=await api.post('/api/upload',form);await api.post('/api/assets',{kind,serverId,name,url:upload.data.url});await refresh();setName('');setFile(null);})}>{translate("Adicionar mídia")}</Action></>}</div>;}
