import {t as translate,useLocale} from '../localization';
import React,{useEffect,useRef,useState} from 'react';
import api from '../api';
import {useSocket} from '../context/SocketContext';
import {useVoice} from '../context/VoiceContext';
import {useAudioPreferences} from '../context/AudioPreferencesContext';
import {useAuth} from '../context/AuthContext';
import {Modal,Action,Notice} from './FormControls';
export function SoundboardPlayer(){
  useLocale();const{socket}=useSocket(),voice=useVoice(),{settings}=useAudioPreferences();const latest=useRef({voice,settings});latest.current={voice,settings};const active=useRef(new Set());useEffect(()=>{if(!socket)return;const play=async data=>{const{voice,settings}=latest.current;if(voice.isDeafened || voice.currentVoiceChannel?.id!==data.channelId || settings.participants[data.userId]?.muted)return;let url,audio;try{const r=await api.get(data.url,{responseType:'blob'});if(latest.current.voice.isDeafened || latest.current.voice.currentVoiceChannel?.id!==data.channelId)return;url=URL.createObjectURL(r.data);audio=new Audio(url);const level=settings.participants[data.userId]?.volume??1;audio.volume=Math.min(1,settings.outputGain*settings.soundboardVolume*level);if(settings.outputDeviceId && audio.setSinkId)await audio.setSinkId(settings.outputDeviceId);const clear=()=>{audio.pause();URL.revokeObjectURL(url);active.current.delete(clear);};active.current.add(clear);audio.onended=clear;audio.onerror=clear;await audio.play();setTimeout(clear,15000);}catch{if(url)URL.revokeObjectURL(url);}};socket.on('soundboard_play',play);return()=>{socket.off('soundboard_play',play);for(const clear of active.current)clear();};},[socket]);useEffect(()=>{if(voice.isDeafened || !voice.currentVoiceChannel)for(const clear of active.current)clear();},[voice.isDeafened,voice.currentVoiceChannel?.id]);return null;}
export default function Soundboard({onClose}){
  useLocale();const{socket}=useSocket(),{currentUser}=useAuth(),{settings,update}=useAudioPreferences(),[sounds,setSounds]=useState([]),[error,setError]=useState(''),[favorite,setFavorite]=useState(()=>{try{return JSON.parse(localStorage.getItem('soundboard:'+currentUser.id)) || [];}catch{return[];}});useEffect(()=>{api.get('/api/assets',{params:{kind:'sound'}}).then(r=>setSounds(r.data)).catch(()=>setError('Não foi possível carregar os sons'));},[]);return <Modal title={translate("Soundboard")} onClose={onClose}><label className="block mb-4">{translate("Volume:")} {Math.round(settings.soundboardVolume*100)}%<input type="range" min={0} max={1} step={0.05} value={settings.soundboardVolume} onChange={e=>update({soundboardVolume:Number(e.target.value)})} className="block w-full"/></label><div className="grid grid-cols-3 gap-3">{[...sounds].sort((a,b)=>Number(favorite.includes(b.id))-Number(favorite.includes(a.id))).map(s=><div key={s.id} className="bg-discord-darker rounded p-3"><Action onClick={async()=>{try{await api.post('/api/soundboard/play',{assetId:s.id,socketId:socket.id});setError('');}catch(e){setError(e.response?.data?.error || 'Som indisponível');}}}>♪ {s.name}</Action><button aria-label={`Favoritar ${s.name}`} onClick={()=>{const value=favorite.includes(s.id)?favorite.filter(id=>id!==s.id):[...favorite,s.id];setFavorite(value);localStorage.setItem('soundboard:'+currentUser.id,JSON.stringify(value));}}>{favorite.includes(s.id)?'★':'☆'}</button></div>)}</div>{!sounds.length&&<p>{translate("Adicione sons em Servidor → Emojis e mídia → Sons.")}</p>}<Notice error={error}/></Modal>;}
