import {app,Tray,Menu,nativeImage,BrowserWindow,ipcMain,globalShortcut,powerMonitor} from 'electron';
import {AudioAttenuation} from './attenuation.js';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import koffi from 'koffi';
import {normalizeDesktopSettings,keyCodes} from './preferences.js';
const directory=fileURLToPath(new URL('.',import.meta.url)),execute=promisify(execFile);
const settingsPath=()=>path.join(app.getPath('userData'),'desktop-preferences.json');
export function readDesktopSettings(){try{return normalizeDesktopSettings(JSON.parse(fs.readFileSync(settingsPath(),'utf8')));}catch{return normalizeDesktopSettings();}}
function trayImage(){const bytes=Buffer.alloc(32*32*4);for(let y=0;y<32;y++)for(let x=0;x<32;x++){const i=(y*32+x)*4,inside=(x-16)**2+(y-16)**2<=15**2;if(inside){bytes[i]=242;bytes[i+1]=101;bytes[i+2]=88;bytes[i+3]=255;}if(inside && y>=8 && y<=24 && (x>=8 && x<=11 || x>=21 && x<=24 || y<=16 && Math.abs(Math.abs(x-16)-(16-y))<2)){bytes[i]=bytes[i+1]=bytes[i+2]=255;bytes[i+3]=255;}}return nativeImage.createFromBitmap(bytes,{width:32,height:32});}
export function installDesktopFeatures({handleTrusted,getWindow,guard,log=()=>{}}) {
  let settings=readDesktopSettings(),tray=null,overlay=null,quitting=false,pttDown=false,keys=[],timer=null,user32=null,runtime={participants:[],messages:[],channel:'',muted:false,deafened:false,sharing:false,active:false},shortcutErrors=[];
  const helper=app.isPackaged?path.join(process.resourcesPath,'app.asar.unpacked','desktop','AudioSessionHost.exe'):path.join(directory,'AudioSessionHost.exe');const attenuation=new AudioAttenuation({helper,excluded:()=>[process.pid,...app.getAppMetrics().map(m=>m.pid)],onError:message=>log(message)});
  const registered=new Set();
  const send=action=>{const window=getWindow();if(window && !window.isDestroyed())window.webContents.send('desktop-action',action);};
  const show=()=>{const window=getWindow();if(window && !window.isDestroyed()){if(window.isMinimized())window.restore();window.show();window.focus();}};
  const quit=()=>{attenuation.close();quitting=true;guard.revoke('Aplicativo encerrando');app.quit();};
  function menu(){if(!tray)return;tray.setContextMenu(Menu.buildFromTemplate([{label:'Abrir MeuApp',click:show},{type:'separator'},{label:'Microfone silenciado',type:'checkbox',checked:runtime.muted,click:()=>send('mute')},{label:'Áudio silenciado',type:'checkbox',checked:runtime.deafened,click:()=>send('deafen')},{label:'Compartilhar tela',click:()=>{show();send('share');}},{label:'Overlay',click:toggleOverlay},{type:'separator'},{label:'Sair',click:quit}]));tray.setToolTip(runtime.active?`MeuApp · ${runtime.channel}`:'MeuApp');}
  function toggleOverlay(){if(!settings.overlayEnabled)return;if(!overlay || overlay.isDestroyed()){overlay=new BrowserWindow({width:330,height:470,frame:false,transparent:true,resizable:true,alwaysOnTop:true,skipTaskbar:true,show:false,webPreferences:{preload:path.join(directory,'overlay-preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,backgroundThrottling:false}});overlay.setContentProtection(true);overlay.setIgnoreMouseEvents(true,{forward:true});overlay.interactive=false;overlay.loadFile(path.join(directory,'overlay.html'));overlay.webContents.setWindowOpenHandler(()=>({action:'deny'}));overlay.webContents.on('will-navigate',e=>e.preventDefault());overlay.once('ready-to-show',()=>{overlay.webContents.send('overlay-state',runtime);overlay.showInactive();});overlay.on('closed',()=>{overlay=null;});}else if(overlay.isVisible())overlay.hide();else{overlay.webContents.send('overlay-state',runtime);overlay.showInactive();}}
  function shortcuts(){for(const binding of registered)globalShortcut.unregister(binding);registered.clear();shortcutErrors=[];const seen=new Set();for(const[action,binding]of Object.entries(settings.shortcuts)){if(!binding)continue;if(seen.has(binding)){shortcutErrors.push(`${binding}: repetido`);continue;}seen.add(binding);const handler=action==='open'?show:action==='overlay'?toggleOverlay:action==='overlayInput'?()=>{if(!overlay || overlay.isDestroyed())return;overlay.interactive=!overlay.interactive;overlay.setIgnoreMouseEvents(!overlay.interactive,{forward:true});if(overlay.interactive){overlay.show();overlay.focus();}else overlay.showInactive();}:()=>{if(action==='share')show();send(action);};try{if(globalShortcut.register(binding,handler))registered.add(binding);else shortcutErrors.push(`${binding}: indisponível`);}catch{shortcutErrors.push(`${binding}: inválido`);}}}
  const attached=new WeakSet();
  function attach(window){if(attached.has(window))return;attached.add(window);window.on('close',event=>{if(!quitting && settings.closeToTray && tray){event.preventDefault();window.hide();}});window.webContents.on('did-finish-load',()=>{if(settings.startMinimized || process.argv.includes('--autostart'))window.hide();});}
  handleTrusted('desktop-get-settings',()=>({...settings,shortcutErrors,packaged:app.isPackaged}));
  handleTrusted('desktop-set-settings',(_event,value)=>{const old=settings,next=normalizeDesktopSettings(value);fs.mkdirSync(path.dirname(settingsPath()),{recursive:true});fs.writeFileSync(settingsPath()+'.tmp',JSON.stringify(next));fs.renameSync(settingsPath()+'.tmp',settingsPath());settings=next;if(old.startWithWindows!==next.startWithWindows && app.isPackaged && !(process.env.MEUAPP_DIAGNOSTICS==='true' && process.argv.some(a=>a.startsWith('--user-data-dir'))))app.setLoginItemSettings({openAtLogin:next.startWithWindows,path:process.execPath,args:['--autostart']});shortcuts();menu();if(!settings.overlayEnabled)overlay?.close();return{...settings,shortcutErrors,requiresRestart:old.hardwareAcceleration!==settings.hardwareAcceleration};});
  handleTrusted('desktop-minimize-tray',()=>{getWindow()?.hide();return true;});
  handleTrusted('desktop-open',()=>{show();return true;});
  handleTrusted('desktop-toggle-overlay',()=>{toggleOverlay();return true;});
  handleTrusted('desktop-restart',()=>{attenuation.close();quitting=true;guard.revoke('Aplicativo reiniciando');app.relaunch();app.exit(0);});
  handleTrusted('desktop-runtime',(_event,value)=>{if(!value || typeof value!=='object')return false;const previous=JSON.stringify(runtime);attenuation.update(value.active===true && value.remoteSpeaking===true && Number.isFinite(value.attenuation)?Math.max(0,Math.min(1,value.attenuation)):0);runtime={chatActive:value.chatActive===true,active:value.active===true,channel:String(value.channel || '').slice(0,100),muted:value.muted===true,deafened:value.deafened===true,sharing:value.sharing===true,participants:Array.isArray(value.participants)?value.participants.slice(0,100).map(p=>({name:String(p.name || '').slice(0,80),speaking:p.speaking===true,muted:p.muted===true,deafened:p.deafened===true})):[],messages:Array.isArray(value.messages)?value.messages.slice(-5).map(m=>({name:String(m.name || '').slice(0,80),text:String(m.text || '').slice(0,240)})):[]};keys=value.ptt?.enabled && runtime.active?keyCodes(value.ptt.binding):[];if(!keys.length && pttDown){pttDown=false;send('ptt_up');}if(previous!==JSON.stringify(runtime)){menu();if(overlay && !overlay.isDestroyed())overlay.webContents.send('overlay-state',runtime);}return true;});
  ipcMain.on('overlay-action',(event,data)=>{if(!overlay || event.sender!==overlay.webContents || event.senderFrame!==overlay.webContents.mainFrame)return;if(data?.action==='chat' && typeof data.text==='string' && data.text.trim() && data.text.length<=4000){const main=getWindow();main?.webContents.send('desktop-quick-chat',data.text);}else if(['mute','deafen','share','open'].includes(data?.action)){if(data.action==='open' || data.action==='share')show();if(data.action!=='open')send(data.action);}else if(data?.action==='close')overlay.hide();});
  handleTrusted('desktop-running-apps',async()=>{if(process.platform!=='win32')return[];const {stdout}=await execute('powershell.exe',['-NoProfile','-NonInteractive','-Command',"[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false); Get-Process | Where-Object { $_.MainWindowHandle -ne 0 } | Select-Object ProcessName,Id,@{Name='StartedAt';Expression={try{$_.StartTime.ToUniversalTime().ToString('o')}catch{''}}} | ConvertTo-Json -Compress"],{windowsHide:true,timeout:5000,maxBuffer:200000});let rows;try{rows=JSON.parse(stdout);}catch{return[];}return(Array.isArray(rows)?rows:[rows]).slice(0,200).filter(r=>typeof r.ProcessName==='string').map(r=>({name:r.ProcessName.slice(0,80),id:r.Id,startedAt:r.StartedAt}));});
  handleTrusted('desktop-idle-seconds',()=>powerMonitor.getSystemIdleTime());
  app.on('before-quit',()=>{quitting=true;attenuation.close();guard.revoke('Aplicativo encerrando');clearInterval(timer);for(const binding of registered)globalShortcut.unregister(binding);registered.clear();overlay?.destroy();tray?.destroy();});
  app.whenReady().then(()=>{tray=new Tray(trayImage());tray.on('double-click',show);tray.on('click',show);menu();shortcuts();const window=getWindow();if(window)attach(window);app.on('browser-window-created',(_event,window)=>{queueMicrotask(()=>{if(window===getWindow())attach(window);});});if(process.platform==='win32'){try{user32=koffi.load('user32.dll');const down=user32.func('short __stdcall GetAsyncKeyState(int key)');timer=setInterval(()=>{if(!keys.length)return;const pressed=keys.every(k=>(down(k)&0x8000)!==0);if(pressed!==pttDown){pttDown=pressed;send(pressed?'ptt_down':'ptt_up');}},25);timer.unref();}catch(e){log('Atalho Push-to-Talk indisponível',{message:e.message});}}});
  return {settings:()=>settings,toggleOverlay,quit};
}
